# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\learningcontent\Suchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lehrstoff_Suche(object):
    def setupUi(self, Lehrstoff_Suche):
        Lehrstoff_Suche.setObjectName("Lehrstoff_Suche")
        Lehrstoff_Suche.resize(713, 450)
        Lehrstoff_Suche.setMinimumSize(QtCore.QSize(713, 450))
        Lehrstoff_Suche.setSizeGripEnabled(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Lehrstoff_Suche)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gB_Suchfelder = QtWidgets.QGroupBox(Lehrstoff_Suche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gB_Suchfelder.sizePolicy().hasHeightForWidth())
        self.gB_Suchfelder.setSizePolicy(sizePolicy)
        self.gB_Suchfelder.setMinimumSize(QtCore.QSize(695, 120))
        self.gB_Suchfelder.setObjectName("gB_Suchfelder")
        self.gridLayout = QtWidgets.QGridLayout(self.gB_Suchfelder)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_Fachgebiet = QtWidgets.QLabel(self.gB_Suchfelder)
        self.lbl_Fachgebiet.setObjectName("lbl_Fachgebiet")
        self.gridLayout.addWidget(self.lbl_Fachgebiet, 0, 0, 1, 1)
        self.le_Fachrichtung = QtWidgets.QLineEdit(self.gB_Suchfelder)
        self.le_Fachrichtung.setObjectName("le_Fachrichtung")
        self.gridLayout.addWidget(self.le_Fachrichtung, 0, 1, 1, 1)
        self.lbl_Verantwortlicher = QtWidgets.QLabel(self.gB_Suchfelder)
        self.lbl_Verantwortlicher.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Verantwortlicher.setObjectName("lbl_Verantwortlicher")
        self.gridLayout.addWidget(self.lbl_Verantwortlicher, 0, 2, 1, 1)
        self.le_Verantwortlicher = QtWidgets.QLineEdit(self.gB_Suchfelder)
        self.le_Verantwortlicher.setObjectName("le_Verantwortlicher")
        self.gridLayout.addWidget(self.le_Verantwortlicher, 0, 3, 1, 1)
        self.lbl_Bezeichnung = QtWidgets.QLabel(self.gB_Suchfelder)
        self.lbl_Bezeichnung.setObjectName("lbl_Bezeichnung")
        self.gridLayout.addWidget(self.lbl_Bezeichnung, 1, 0, 1, 1)
        self.le_Bezeichnung = QtWidgets.QLineEdit(self.gB_Suchfelder)
        self.le_Bezeichnung.setObjectName("le_Bezeichnung")
        self.gridLayout.addWidget(self.le_Bezeichnung, 1, 1, 1, 3)
        self.gridLayout_2.addWidget(self.gB_Suchfelder, 0, 0, 1, 1)
        self.tW_Lehrstoff_DB = QtWidgets.QTableWidget(Lehrstoff_Suche)
        self.tW_Lehrstoff_DB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tW_Lehrstoff_DB.setObjectName("tW_Lehrstoff_DB")
        self.tW_Lehrstoff_DB.setColumnCount(0)
        self.tW_Lehrstoff_DB.setRowCount(0)
        self.gridLayout_2.addWidget(self.tW_Lehrstoff_DB, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(500)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_Suchen = QtWidgets.QPushButton(Lehrstoff_Suche)
        self.pB_Suchen.setMaximumSize(QtCore.QSize(100, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Python\\Projekte\\Knapp_Apprentice_Training\\sub\\learningcontent\\../../_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Suchen.setIcon(icon)
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.horizontalLayout.addWidget(self.pB_Suchen)
        self.pB_Beenden = QtWidgets.QPushButton(Lehrstoff_Suche)
        self.pB_Beenden.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Python\\Projekte\\Knapp_Apprentice_Training\\sub\\learningcontent\\../../_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon1)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.horizontalLayout.addWidget(self.pB_Beenden)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Lehrstoff_Suche)
        QtCore.QMetaObject.connectSlotsByName(Lehrstoff_Suche)

    def retranslateUi(self, Lehrstoff_Suche):
        _translate = QtCore.QCoreApplication.translate
        Lehrstoff_Suche.setWindowTitle(_translate("Lehrstoff_Suche", "Suche"))
        self.gB_Suchfelder.setTitle(_translate("Lehrstoff_Suche", "Suchfelder"))
        self.lbl_Fachgebiet.setText(_translate("Lehrstoff_Suche", "Fachrichtung:"))
        self.lbl_Verantwortlicher.setText(_translate("Lehrstoff_Suche", "Verantwortlicher:"))
        self.lbl_Bezeichnung.setText(_translate("Lehrstoff_Suche", "Bezeichnung:"))
        self.pB_Suchen.setText(_translate("Lehrstoff_Suche", "Suchen"))
        self.pB_Beenden.setText(_translate("Lehrstoff_Suche", "Beenden"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lehrstoff_Suche = QtWidgets.QDialog()
    ui = Ui_Lehrstoff_Suche()
    ui.setupUi(Lehrstoff_Suche)
    Lehrstoff_Suche.show()
    sys.exit(app.exec_())
