# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\hinzufuegen_Plan.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(520, 629)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.Wochen_Tag = QtWidgets.QLabel(Dialog)
        self.Wochen_Tag.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.Wochen_Tag.setObjectName("Wochen_Tag")
        self.horizontalLayout_12.addWidget(self.Wochen_Tag)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.timeEdit_von = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit_von.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeEdit_von.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.timeEdit_von.setObjectName("timeEdit_von")
        self.horizontalLayout_12.addWidget(self.timeEdit_von)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.timeEdit_bis = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit_bis.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeEdit_bis.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.timeEdit_bis.setObjectName("timeEdit_bis")
        self.horizontalLayout_12.addWidget(self.timeEdit_bis)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.comboBox_Unterrichtsthema = QtWidgets.QComboBox(Dialog)
        self.comboBox_Unterrichtsthema.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_Unterrichtsthema.setEditable(True)
        self.comboBox_Unterrichtsthema.setObjectName("comboBox_Unterrichtsthema")
        self.comboBox_Unterrichtsthema.addItem("")
        self.comboBox_Unterrichtsthema.setItemText(0, "")
        self.horizontalLayout_4.addWidget(self.comboBox_Unterrichtsthema)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_ausbilder = QtWidgets.QComboBox(Dialog)
        self.comboBox_ausbilder.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_ausbilder.setObjectName("comboBox_ausbilder")
        self.comboBox_ausbilder.addItem("")
        self.comboBox_ausbilder.setItemText(0, "")
        self.horizontalLayout_5.addWidget(self.comboBox_ausbilder)
        self.le_vorname = QtWidgets.QLineEdit(Dialog)
        self.le_vorname.setEnabled(False)
        self.le_vorname.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_vorname.setObjectName("le_vorname")
        self.horizontalLayout_5.addWidget(self.le_vorname)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_raum = QtWidgets.QComboBox(Dialog)
        self.comboBox_raum.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_raum.setObjectName("comboBox_raum")
        self.comboBox_raum.addItem("")
        self.comboBox_raum.setItemText(0, "")
        self.horizontalLayout.addWidget(self.comboBox_raum)
        self.le_raum = QtWidgets.QLineEdit(Dialog)
        self.le_raum.setEnabled(False)
        self.le_raum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_raum.setObjectName("le_raum")
        self.horizontalLayout.addWidget(self.le_raum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_1A = QtWidgets.QCheckBox(Dialog)
        self.checkBox_1A.setObjectName("checkBox_1A")
        self.verticalLayout_2.addWidget(self.checkBox_1A)
        self.checkBox_1B = QtWidgets.QCheckBox(Dialog)
        self.checkBox_1B.setObjectName("checkBox_1B")
        self.verticalLayout_2.addWidget(self.checkBox_1B)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_2A = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2A.setObjectName("checkBox_2A")
        self.verticalLayout_3.addWidget(self.checkBox_2A)
        self.checkBox_2B = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2B.setObjectName("checkBox_2B")
        self.verticalLayout_3.addWidget(self.checkBox_2B)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_3A = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3A.setObjectName("checkBox_3A")
        self.verticalLayout_4.addWidget(self.checkBox_3A)
        self.checkBox_3B = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3B.setObjectName("checkBox_3B")
        self.verticalLayout_4.addWidget(self.checkBox_3B)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_4A = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4A.setObjectName("checkBox_4A")
        self.verticalLayout_5.addWidget(self.checkBox_4A)
        self.checkBox_4B = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4B.setObjectName("checkBox_4B")
        self.verticalLayout_5.addWidget(self.checkBox_4B)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.pushButton_einzelne_lehrlinge = QtWidgets.QPushButton(Dialog)
        self.pushButton_einzelne_lehrlinge.setMinimumSize(QtCore.QSize(355, 0))
        self.pushButton_einzelne_lehrlinge.setObjectName("pushButton_einzelne_lehrlinge")
        self.horizontalLayout_16.addWidget(self.pushButton_einzelne_lehrlinge)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 110))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 465, 89))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(40, 40))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.comboBox_thema1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_thema1.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_thema1.setObjectName("comboBox_thema1")
        self.comboBox_thema1.addItem("")
        self.comboBox_thema1.setItemText(0, "")
        self.horizontalLayout_6.addWidget(self.comboBox_thema1)
        self.sb_Thema1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema1.setEnabled(False)
        self.sb_Thema1.setObjectName("sb_Thema1")
        self.horizontalLayout_6.addWidget(self.sb_Thema1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(40, 40))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.comboBox_thema2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_thema2.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_thema2.setObjectName("comboBox_thema2")
        self.comboBox_thema2.addItem("")
        self.comboBox_thema2.setItemText(0, "")
        self.horizontalLayout_7.addWidget(self.comboBox_thema2)
        self.sb_Thema2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema2.setEnabled(False)
        self.sb_Thema2.setObjectName("sb_Thema2")
        self.horizontalLayout_7.addWidget(self.sb_Thema2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.comboBox_thema3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_thema3.setEnabled(True)
        self.comboBox_thema3.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_thema3.setObjectName("comboBox_thema3")
        self.comboBox_thema3.addItem("")
        self.comboBox_thema3.setItemText(0, "")
        self.horizontalLayout_8.addWidget(self.comboBox_thema3)
        self.sb_Thema3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema3.setEnabled(False)
        self.sb_Thema3.setObjectName("sb_Thema3")
        self.horizontalLayout_8.addWidget(self.sb_Thema3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setMinimumSize(QtCore.QSize(420, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.gesamt_stunden = QtWidgets.QLineEdit(Dialog)
        self.gesamt_stunden.setEnabled(False)
        self.gesamt_stunden.setObjectName("gesamt_stunden")
        self.horizontalLayout_9.addWidget(self.gesamt_stunden)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.te_vorschau = QtWidgets.QTableWidget(Dialog)
        self.te_vorschau.setMinimumSize(QtCore.QSize(0, 130))
        self.te_vorschau.setTabletTracking(False)
        self.te_vorschau.setFocusPolicy(QtCore.Qt.NoFocus)
        self.te_vorschau.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.te_vorschau.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.te_vorschau.setAutoFillBackground(True)
        self.te_vorschau.setFrameShape(QtWidgets.QFrame.Box)
        self.te_vorschau.setFrameShadow(QtWidgets.QFrame.Plain)
        self.te_vorschau.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.te_vorschau.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.te_vorschau.setTextElideMode(QtCore.Qt.ElideRight)
        self.te_vorschau.setShowGrid(True)
        self.te_vorschau.setGridStyle(QtCore.Qt.NoPen)
        self.te_vorschau.setObjectName("te_vorschau")
        self.te_vorschau.setColumnCount(1)
        self.te_vorschau.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.te_vorschau.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.te_vorschau.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.te_vorschau.setItem(2, 0, item)
        self.verticalLayout_9.addWidget(self.te_vorschau)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_hinzufuegen = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/add_insert_new_plus_icon_148990.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hinzufuegen.setIcon(icon)
        self.pushButton_hinzufuegen.setObjectName("pushButton_hinzufuegen")
        self.horizontalLayout_2.addWidget(self.pushButton_hinzufuegen)
        self.pushButton_abbrechen = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abbrechen.setIcon(icon1)
        self.pushButton_abbrechen.setObjectName("pushButton_abbrechen")
        self.horizontalLayout_2.addWidget(self.pushButton_abbrechen)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Tag:"))
        self.Wochen_Tag.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "UNTERRICHT"))
        self.label_11.setText(_translate("Dialog", "von"))
        self.label_13.setText(_translate("Dialog", "bis"))
        self.label_7.setText(_translate("Dialog", "Unterrichtsthema"))
        self.label_6.setText(_translate("Dialog", "Ausbilder"))
        self.label.setText(_translate("Dialog", "Raum"))
        self.label_5.setText(_translate("Dialog", "Gruppen/LJ/Beruf"))
        self.checkBox_1A.setText(_translate("Dialog", "1A"))
        self.checkBox_1B.setText(_translate("Dialog", "1B"))
        self.checkBox_2A.setText(_translate("Dialog", "2A"))
        self.checkBox_2B.setText(_translate("Dialog", "2B"))
        self.checkBox_3A.setText(_translate("Dialog", "3A"))
        self.checkBox_3B.setText(_translate("Dialog", "3B"))
        self.checkBox_4A.setText(_translate("Dialog", "4A"))
        self.checkBox_4B.setText(_translate("Dialog", "4B"))
        self.label_4.setText(_translate("Dialog", "Einzelne Lehrlinge"))
        self.pushButton_einzelne_lehrlinge.setText(_translate("Dialog", "Auswählen..."))
        self.label_3.setText(_translate("Dialog", "Sonstige Information"))
        self.groupBox.setTitle(_translate("Dialog", "Themen/Lerstoff                                                                                                                    Stunden"))
        self.label_14.setText(_translate("Dialog", "Thema 1"))
        self.sb_Thema1.setText(_translate("Dialog", "0"))
        self.label_18.setText(_translate("Dialog", "Thema 2"))
        self.sb_Thema2.setText(_translate("Dialog", "0"))
        self.label_17.setText(_translate("Dialog", "Thema 3"))
        self.sb_Thema3.setText(_translate("Dialog", "0"))
        self.label_19.setText(_translate("Dialog", "                                                                                                                                              "))
        self.label_12.setText(_translate("Dialog", "Vorschau"))
        __sortingEnabled = self.te_vorschau.isSortingEnabled()
        self.te_vorschau.setSortingEnabled(False)
        self.te_vorschau.setSortingEnabled(__sortingEnabled)
        self.pushButton_hinzufuegen.setText(_translate("Dialog", "Hinzufügen"))
        self.pushButton_abbrechen.setText(_translate("Dialog", "Abbrechen"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
