# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\Wochen_Unterricht.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(668, 462)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_befor_KW = QtWidgets.QPushButton(Dialog)
        self.pushButton_befor_KW.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-left-arrow-button_icon-icons.com_72692.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_befor_KW.setIcon(icon)
        self.pushButton_befor_KW.setObjectName("pushButton_befor_KW")
        self.gridLayout.addWidget(self.pushButton_befor_KW, 1, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_Wochen_Plan = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_Wochen_Plan.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget_Wochen_Plan.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget_Wochen_Plan.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_Wochen_Plan.setLineWidth(1)
        self.tableWidget_Wochen_Plan.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_Wochen_Plan.setAutoScrollMargin(16)
        self.tableWidget_Wochen_Plan.setShowGrid(True)
        self.tableWidget_Wochen_Plan.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Wochen_Plan.setRowCount(12)
        self.tableWidget_Wochen_Plan.setObjectName("tableWidget_Wochen_Plan")
        self.tableWidget_Wochen_Plan.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Wochen_Plan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Wochen_Plan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Wochen_Plan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Wochen_Plan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Wochen_Plan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(32)
        item.setFont(font)
        self.tableWidget_Wochen_Plan.setItem(7, 3, item)
        self.verticalLayout.addWidget(self.tableWidget_Wochen_Plan)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_hauptmenue = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/Icons/computer/log_out.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hauptmenue.setIcon(icon1)
        self.pushButton_hauptmenue.setObjectName("pushButton_hauptmenue")
        self.horizontalLayout.addWidget(self.pushButton_hauptmenue)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/copyblackinterfacesymboloftwopapersheets_79854.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_excel_ausgabe = QtWidgets.QPushButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/microsoft_excel_icon_132212.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_excel_ausgabe.setIcon(icon3)
        self.pushButton_excel_ausgabe.setObjectName("pushButton_excel_ausgabe")
        self.horizontalLayout.addWidget(self.pushButton_excel_ausgabe)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_Hilfe = QtWidgets.QPushButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/info_13213.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Hilfe.setIcon(icon4)
        self.pushButton_Hilfe.setObjectName("pushButton_Hilfe")
        self.horizontalLayout.addWidget(self.pushButton_Hilfe)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 7)
        self.te_KW = QtWidgets.QLabel(Dialog)
        self.te_KW.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.te_KW.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.te_KW.setAlignment(QtCore.Qt.AlignCenter)
        self.te_KW.setObjectName("te_KW")
        self.gridLayout.addWidget(self.te_KW, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_jahr = QtWidgets.QLabel(Dialog)
        self.label_jahr.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_jahr.setObjectName("label_jahr")
        self.gridLayout.addWidget(self.label_jahr, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_next_KW = QtWidgets.QPushButton(Dialog)
        self.pushButton_next_KW.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-right-arrow-button-1_icon-icons.com_72690.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_KW.setIcon(icon5)
        self.pushButton_next_KW.setObjectName("pushButton_next_KW")
        self.gridLayout.addWidget(self.pushButton_next_KW, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tableWidget_Wochen_Plan.setSortingEnabled(False)
        item = self.tableWidget_Wochen_Plan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Montag"))
        item = self.tableWidget_Wochen_Plan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Dienstag"))
        item = self.tableWidget_Wochen_Plan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Mittwoch"))
        item = self.tableWidget_Wochen_Plan.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Donnerstag"))
        item = self.tableWidget_Wochen_Plan.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Freitag"))
        __sortingEnabled = self.tableWidget_Wochen_Plan.isSortingEnabled()
        self.tableWidget_Wochen_Plan.setSortingEnabled(False)
        self.tableWidget_Wochen_Plan.setSortingEnabled(__sortingEnabled)
        self.pushButton_hauptmenue.setText(_translate("Dialog", "Hauptmenü"))
        self.pushButton.setText(_translate("Dialog", "Kopieren"))
        self.pushButton_excel_ausgabe.setText(_translate("Dialog", "Excel ausgabe"))
        self.pushButton_Hilfe.setText(_translate("Dialog", "Hilfe"))
        self.te_KW.setText(_translate("Dialog", "."))
        self.label_jahr.setText(_translate("Dialog", "."))
        self.label.setText(_translate("Dialog", "Wochen Unterricht"))
        self.label_4.setText(_translate("Dialog", "KW"))
        self.label_5.setText(_translate("Dialog", "Jahrl"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
