# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\projects\Python\V1.6\Knapp_Apprentice_Training\sub\passwortAendern\passwortAendern.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 228)
        Dialog.setStyleSheet("/*QPushButton::!enabled{\n"
"font-color: rgb(230,230,230)\n"
"}*/\n"
"QLineEdit::!enabled{\n"
"background-color: rgb(230,230,230)\n"
"}")
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.le_altesPasswort = QtWidgets.QLineEdit(Dialog)
        self.le_altesPasswort.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_altesPasswort.setFont(font)
        self.le_altesPasswort.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_altesPasswort.setObjectName("le_altesPasswort")
        self.gridLayout.addWidget(self.le_altesPasswort, 1, 1, 1, 1)
        self.pushButton_aendern = QtWidgets.QPushButton(Dialog)
        self.pushButton_aendern.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_aendern.setFont(font)
        self.pushButton_aendern.setObjectName("pushButton_aendern")
        self.gridLayout.addWidget(self.pushButton_aendern, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.le_Benutzername = QtWidgets.QLineEdit(Dialog)
        self.le_Benutzername.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_Benutzername.setFont(font)
        self.le_Benutzername.setObjectName("le_Benutzername")
        self.gridLayout.addWidget(self.le_Benutzername, 0, 1, 1, 1)
        self.le_neuesPasswort = QtWidgets.QLineEdit(Dialog)
        self.le_neuesPasswort.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_neuesPasswort.setFont(font)
        self.le_neuesPasswort.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_neuesPasswort.setObjectName("le_neuesPasswort")
        self.gridLayout.addWidget(self.le_neuesPasswort, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_passwortBestaetigen = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_passwortBestaetigen.setFont(font)
        self.le_passwortBestaetigen.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_passwortBestaetigen.setObjectName("le_passwortBestaetigen")
        self.gridLayout.addWidget(self.le_passwortBestaetigen, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Passwort ändern"))
        self.pushButton_aendern.setText(_translate("Dialog", "Ändern"))
        self.label.setText(_translate("Dialog", "Benutzername:"))
        self.label_2.setText(_translate("Dialog", "Altes Passwort:"))
        self.label_3.setText(_translate("Dialog", "Neues Passwort:"))
        self.label_4.setText(_translate("Dialog", "Passwort bestätigen:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
