# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\Anwesenheit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 520)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Vorname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Vorname.setEnabled(False)
        self.lineEdit_Vorname.setObjectName("lineEdit_Vorname")
        self.horizontalLayout_2.addWidget(self.lineEdit_Vorname)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_Nachname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Nachname.setEnabled(False)
        self.lineEdit_Nachname.setObjectName("lineEdit_Nachname")
        self.horizontalLayout_3.addWidget(self.lineEdit_Nachname)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_Abwesenheit = QtWidgets.QComboBox(Dialog)
        self.comboBox_Abwesenheit.setEditable(True)
        self.comboBox_Abwesenheit.setObjectName("comboBox_Abwesenheit")
        self.horizontalLayout_4.addWidget(self.comboBox_Abwesenheit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_Alle_Anwesend = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Alle_Anwesend.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_Alle_Anwesend.setObjectName("checkBox_Alle_Anwesend")
        self.horizontalLayout_5.addWidget(self.checkBox_Alle_Anwesend)
        self.pushButton_Speichern_Abwesenheit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Speichern_Abwesenheit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/save_3621.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Speichern_Abwesenheit.setIcon(icon)
        self.pushButton_Speichern_Abwesenheit.setObjectName("pushButton_Speichern_Abwesenheit")
        self.horizontalLayout_5.addWidget(self.pushButton_Speichern_Abwesenheit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Abbrechen = QtWidgets.QPushButton(Dialog)
        self.pushButton_Abbrechen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Abbrechen.setIcon(icon1)
        self.pushButton_Abbrechen.setObjectName("pushButton_Abbrechen")
        self.horizontalLayout.addWidget(self.pushButton_Abbrechen)
        self.pushButton_Speichern = QtWidgets.QPushButton(Dialog)
        self.pushButton_Speichern.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_Speichern.setIcon(icon)
        self.pushButton_Speichern.setObjectName("pushButton_Speichern")
        self.horizontalLayout.addWidget(self.pushButton_Speichern)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Anwesenheit/Abwesenheit"))
        self.label_2.setText(_translate("Dialog", "Vorname"))
        self.label_3.setText(_translate("Dialog", "Nachname"))
        self.label_4.setText(_translate("Dialog", "Abwesenheit wegen"))
        self.checkBox_Alle_Anwesend.setText(_translate("Dialog", "Alle anwesend"))
        self.pushButton_Speichern_Abwesenheit.setText(_translate("Dialog", "Speichern"))
        self.pushButton_Abbrechen.setText(_translate("Dialog", "Abbrechen"))
        self.pushButton_Speichern.setText(_translate("Dialog", "Speichern"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
