# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\thanner\Desktop\Knapp_Apprentice_Training\sub\trainer\Ausbilder_suchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ausbilder_suchen(object):
    def setupUi(self, Ausbilder_suchen):
        Ausbilder_suchen.setObjectName("Ausbilder_suchen")
        Ausbilder_suchen.resize(871, 771)
        Ausbilder_suchen.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Ausbilder_suchen)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 853, 601))
        self.groupBox.setObjectName("groupBox")
        self.tw_suchen = QtWidgets.QTableWidget(self.groupBox)
        self.tw_suchen.setGeometry(QtCore.QRect(10, 20, 831, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_suchen.sizePolicy().hasHeightForWidth())
        self.tw_suchen.setSizePolicy(sizePolicy)
        self.tw_suchen.setObjectName("tw_suchen")
        self.tw_suchen.setColumnCount(0)
        self.tw_suchen.setRowCount(0)
        self.groupBox_2 = QtWidgets.QGroupBox(Ausbilder_suchen)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 853, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_suche = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_suche.setGeometry(QtCore.QRect(80, 30, 761, 20))
        self.le_suche.setObjectName("le_suche")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pb_suchen = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_suchen.setGeometry(QtCore.QRect(340, 70, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_suchen.setIcon(icon)
        self.pb_suchen.setObjectName("pb_suchen")
        self.pb_abbrechen = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_abbrechen.setGeometry(QtCore.QRect(440, 70, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_abbrechen.setIcon(icon1)
        self.pb_abbrechen.setObjectName("pb_abbrechen")
        self.line = QtWidgets.QFrame(Ausbilder_suchen)
        self.line.setGeometry(QtCore.QRect(-420, 110, 1541, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.l_info = QtWidgets.QLabel(Ausbilder_suchen)
        self.l_info.setGeometry(QtCore.QRect(10, 740, 851, 31))
        self.l_info.setText("")
        self.l_info.setObjectName("l_info")

        self.retranslateUi(Ausbilder_suchen)
        QtCore.QMetaObject.connectSlotsByName(Ausbilder_suchen)

    def retranslateUi(self, Ausbilder_suchen):
        _translate = QtCore.QCoreApplication.translate
        Ausbilder_suchen.setWindowTitle(_translate("Ausbilder_suchen", "Dialog"))
        self.groupBox.setTitle(_translate("Ausbilder_suchen", "Suchergebnis(e)"))
        self.groupBox_2.setTitle(_translate("Ausbilder_suchen", "Suche nach"))
        self.label_2.setText(_translate("Ausbilder_suchen", "Suchebgriff:"))
        self.pb_suchen.setText(_translate("Ausbilder_suchen", "Suchen"))
        self.pb_abbrechen.setText(_translate("Ausbilder_suchen", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ausbilder_suchen = QtWidgets.QDialog()
    ui = Ui_Ausbilder_suchen()
    ui.setupUi(Ausbilder_suchen)
    Ausbilder_suchen.show()
    sys.exit(app.exec_())
