# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Beispiele\GUISandbox\SomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 275)
        Dialog.setSizeGripEnabled(True)
        self.pushBtn_pushme = QtWidgets.QPushButton(Dialog)
        self.pushBtn_pushme.setGeometry(QtCore.QRect(130, 90, 141, 81))
        self.pushBtn_pushme.setObjectName("pushBtn_pushme")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushBtn_pushme.setText(_translate("Dialog", "Push Me!"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
