# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Koele - Unterricht\Quantschnig IT\Pyhton\Beispiele\Knapp_Apprentice_Training\sub\bs\Bs_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suche(object):
    def setupUi(self, Suche):
        Suche.setObjectName("Suche")
        Suche.resize(678, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Suche.sizePolicy().hasHeightForWidth())
        Suche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Suche.setFont(font)
        Suche.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Suche)
        self.gridLayout.setObjectName("gridLayout")
        self.leRaeume = QtWidgets.QLineEdit(Suche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leRaeume.sizePolicy().hasHeightForWidth())
        self.leRaeume.setSizePolicy(sizePolicy)
        self.leRaeume.setMinimumSize(QtCore.QSize(520, 20))
        self.leRaeume.setObjectName("leRaeume")
        self.gridLayout.addWidget(self.leRaeume, 1, 1, 1, 1)
        self.tb_Raeume = QtWidgets.QTableWidget(Suche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_Raeume.sizePolicy().hasHeightForWidth())
        self.tb_Raeume.setSizePolicy(sizePolicy)
        self.tb_Raeume.setMinimumSize(QtCore.QSize(660, 550))
        self.tb_Raeume.setObjectName("tb_Raeume")
        self.tb_Raeume.setColumnCount(0)
        self.tb_Raeume.setRowCount(0)
        self.gridLayout.addWidget(self.tb_Raeume, 6, 0, 1, 2)
        self.label = QtWidgets.QLabel(Suche)
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Suche)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 32))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pB_Beenden = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Beenden.sizePolicy().hasHeightForWidth())
        self.pB_Beenden.setSizePolicy(sizePolicy)
        self.pB_Beenden.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Beenden.setMaximumSize(QtCore.QSize(120, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.gridLayout_2.addWidget(self.pB_Beenden, 0, 2, 1, 1)
        self.pB_Suchen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pB_Suchen.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Suchen.setMaximumSize(QtCore.QSize(120, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Suchen.setIcon(icon1)
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.gridLayout_2.addWidget(self.pB_Suchen, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 0, 1, 2)

        self.retranslateUi(Suche)
        QtCore.QMetaObject.connectSlotsByName(Suche)
        Suche.setTabOrder(self.leRaeume, self.tb_Raeume)
        Suche.setTabOrder(self.tb_Raeume, self.pB_Suchen)
        Suche.setTabOrder(self.pB_Suchen, self.pB_Beenden)

    def retranslateUi(self, Suche):
        _translate = QtCore.QCoreApplication.translate
        Suche.setWindowTitle(_translate("Suche", "Suche"))
        self.label.setText(_translate("Suche", "Personal-Nummer:"))
        self.pB_Beenden.setText(_translate("Suche", "Beenden"))
        self.pB_Suchen.setText(_translate("Suche", "Suchen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Suche = QtWidgets.QDialog()
    ui = Ui_Suche()
    ui.setupUi(Suche)
    Suche.show()
    sys.exit(app.exec_())
