# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\projects\Python\V1.7\Knapp_Apprentice_Training\sub\trainer\Ausbilder_suchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ausbilder_suchen(object):
    def setupUi(self, Ausbilder_suchen):
        Ausbilder_suchen.setObjectName("Ausbilder_suchen")
        Ausbilder_suchen.resize(871, 433)
        font = QtGui.QFont()
        font.setPointSize(10)
        Ausbilder_suchen.setFont(font)
        Ausbilder_suchen.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ausbilder_suchen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Ausbilder_suchen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(853, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_suche = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_suche.setGeometry(QtCore.QRect(110, 30, 731, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_suche.setFont(font)
        self.le_suche.setObjectName("le_suche")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_suchen = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_suchen.setGeometry(QtCore.QRect(314, 70, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_suchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_suchen.setIcon(icon)
        self.pb_suchen.setObjectName("pb_suchen")
        self.pb_abbrechen = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_abbrechen.setGeometry(QtCore.QRect(440, 70, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_abbrechen.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_abbrechen.setIcon(icon1)
        self.pb_abbrechen.setObjectName("pb_abbrechen")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tw_suchen = QtWidgets.QTableWidget(Ausbilder_suchen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_suchen.sizePolicy().hasHeightForWidth())
        self.tw_suchen.setSizePolicy(sizePolicy)
        self.tw_suchen.setMinimumSize(QtCore.QSize(831, 281))
        self.tw_suchen.setObjectName("tw_suchen")
        self.tw_suchen.setColumnCount(0)
        self.tw_suchen.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_suchen)
        self.l_info = QtWidgets.QLabel(Ausbilder_suchen)
        self.l_info.setText("")
        self.l_info.setObjectName("l_info")
        self.verticalLayout.addWidget(self.l_info)

        self.retranslateUi(Ausbilder_suchen)
        QtCore.QMetaObject.connectSlotsByName(Ausbilder_suchen)

    def retranslateUi(self, Ausbilder_suchen):
        _translate = QtCore.QCoreApplication.translate
        Ausbilder_suchen.setWindowTitle(_translate("Ausbilder_suchen", "Suchen"))
        self.groupBox_2.setTitle(_translate("Ausbilder_suchen", "Suche nach"))
        self.label_2.setText(_translate("Ausbilder_suchen", "Suchebgriff:"))
        self.pb_suchen.setText(_translate("Ausbilder_suchen", "Suchen"))
        self.pb_abbrechen.setText(_translate("Ausbilder_suchen", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ausbilder_suchen = QtWidgets.QDialog()
    ui = Ui_Ausbilder_suchen()
    ui.setupUi(Ausbilder_suchen)
    Ausbilder_suchen.show()
    sys.exit(app.exec_())
