# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\apprentice\apprentice_manager.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApprenticeManager(object):
    def setupUi(self, ApprenticeManager):
        ApprenticeManager.setObjectName("ApprenticeManager")
        ApprenticeManager.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(ApprenticeManager)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_vor_nach_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_vor_nach_name.setFont(font)
        self.label_vor_nach_name.setObjectName("label_vor_nach_name")
        self.horizontalLayout_2.addWidget(self.label_vor_nach_name)
        self.label_personalnummer = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_personalnummer.setFont(font)
        self.label_personalnummer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_personalnummer.setObjectName("label_personalnummer")
        self.horizontalLayout_2.addWidget(self.label_personalnummer)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.apprentice_tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.apprentice_tabWidget.setObjectName("apprentice_tabWidget")
        self.stammdaten = QtWidgets.QWidget()
        self.stammdaten.setObjectName("stammdaten")
        self.groupBox = QtWidgets.QGroupBox(self.stammdaten)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 351, 191))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_lj = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_lj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lj.setObjectName("label_lj")
        self.horizontalLayout_4.addWidget(self.label_lj)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_lehrberuf = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_lehrberuf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lehrberuf.setObjectName("label_lehrberuf")
        self.horizontalLayout_5.addWidget(self.label_lehrberuf)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_hauptmodul = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_hauptmodul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hauptmodul.setObjectName("label_hauptmodul")
        self.horizontalLayout_6.addWidget(self.label_hauptmodul)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.labe_spezialmodul = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labe_spezialmodul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labe_spezialmodul.setObjectName("labe_spezialmodul")
        self.horizontalLayout_7.addWidget(self.labe_spezialmodul)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.label_lehrbeginn = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_lehrbeginn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lehrbeginn.setObjectName("label_lehrbeginn")
        self.horizontalLayout_8.addWidget(self.label_lehrbeginn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_lehrdauer = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_lehrdauer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lehrdauer.setObjectName("label_lehrdauer")
        self.horizontalLayout_9.addWidget(self.label_lehrdauer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.stammdaten)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 110, 351, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 331, 131))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.label_strasse = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_strasse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_strasse.setObjectName("label_strasse")
        self.horizontalLayout_11.addWidget(self.label_strasse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.label_hausnummer = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_hausnummer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hausnummer.setObjectName("label_hausnummer")
        self.horizontalLayout_12.addWidget(self.label_hausnummer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.label_plz = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_plz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_plz.setObjectName("label_plz")
        self.horizontalLayout_13.addWidget(self.label_plz)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.label_ort = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_ort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ort.setObjectName("label_ort")
        self.horizontalLayout_14.addWidget(self.label_ort)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.label_lkz = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_lkz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lkz.setObjectName("label_lkz")
        self.horizontalLayout_15.addWidget(self.label_lkz)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.stammdaten)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 20, 351, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 331, 51))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_17.addWidget(self.label_25)
        self.label_mail = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_mail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mail.setObjectName("label_mail")
        self.horizontalLayout_17.addWidget(self.label_mail)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.label_telefonnummer = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_telefonnummer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_telefonnummer.setObjectName("label_telefonnummer")
        self.horizontalLayout_18.addWidget(self.label_telefonnummer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.stammdaten)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 351, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 331, 59))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_23.addWidget(self.label_33)
        self.label_geburtsdatum = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_geburtsdatum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_geburtsdatum.setObjectName("label_geburtsdatum")
        self.horizontalLayout_23.addWidget(self.label_geburtsdatum)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_24.addWidget(self.label_35)
        self.label_geschlecht = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_geschlecht.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_geschlecht.setObjectName("label_geschlecht")
        self.horizontalLayout_24.addWidget(self.label_geschlecht)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_22.addLayout(self.verticalLayout_6)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.stammdaten)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(8, 410, 761, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_lehrling_loeschen = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_lehrling_loeschen.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pic/delete-user_96969.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_lehrling_loeschen.setIcon(icon)
        self.pushButton_lehrling_loeschen.setObjectName("pushButton_lehrling_loeschen")
        self.horizontalLayout_25.addWidget(self.pushButton_lehrling_loeschen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.pushButton_stammdaten_bearbeiten = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_stammdaten_bearbeiten.setObjectName("pushButton_stammdaten_bearbeiten")
        self.horizontalLayout_25.addWidget(self.pushButton_stammdaten_bearbeiten)
        self.apprentice_tabWidget.addTab(self.stammdaten, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.apprentice_tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.apprentice_tabWidget)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pushButton_alle_lehrlinge = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_alle_lehrlinge.setObjectName("pushButton_alle_lehrlinge")
        self.verticalLayout.addWidget(self.pushButton_alle_lehrlinge)

        self.retranslateUi(ApprenticeManager)
        self.apprentice_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApprenticeManager)

    def retranslateUi(self, ApprenticeManager):
        _translate = QtCore.QCoreApplication.translate
        ApprenticeManager.setWindowTitle(_translate("ApprenticeManager", "Lehrling"))
        self.label_vor_nach_name.setText(_translate("ApprenticeManager", "Max Mustermann"))
        self.label_personalnummer.setText(_translate("ApprenticeManager", "LJ4"))
        self.groupBox.setTitle(_translate("ApprenticeManager", "Knapp:"))
        self.label_4.setText(_translate("ApprenticeManager", "Lehrjahr:"))
        self.label_lj.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_5.setText(_translate("ApprenticeManager", "Lehrberuf:"))
        self.label_lehrberuf.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_7.setText(_translate("ApprenticeManager", "Hauptmodul:"))
        self.label_hauptmodul.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_9.setText(_translate("ApprenticeManager", "Spezialmodul:"))
        self.labe_spezialmodul.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_11.setText(_translate("ApprenticeManager", "Lehrbeginn:"))
        self.label_lehrbeginn.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_13.setText(_translate("ApprenticeManager", "Lehrdauer:"))
        self.label_lehrdauer.setText(_translate("ApprenticeManager", "TextLabel"))
        self.groupBox_2.setTitle(_translate("ApprenticeManager", "Adresse:"))
        self.label_15.setText(_translate("ApprenticeManager", "Straße:"))
        self.label_strasse.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_17.setText(_translate("ApprenticeManager", "Hausnummer:"))
        self.label_hausnummer.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_19.setText(_translate("ApprenticeManager", "PLZ:"))
        self.label_plz.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_21.setText(_translate("ApprenticeManager", "Ort:"))
        self.label_ort.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_23.setText(_translate("ApprenticeManager", "LKZ:"))
        self.label_lkz.setText(_translate("ApprenticeManager", "TextLabel"))
        self.groupBox_3.setTitle(_translate("ApprenticeManager", "Kontakt:"))
        self.label_25.setText(_translate("ApprenticeManager", "Mail:"))
        self.label_mail.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_27.setText(_translate("ApprenticeManager", "Telefonnummer:"))
        self.label_telefonnummer.setText(_translate("ApprenticeManager", "TextLabel"))
        self.groupBox_4.setTitle(_translate("ApprenticeManager", "Persönliches:"))
        self.label_33.setText(_translate("ApprenticeManager", "Geburtsdatum:"))
        self.label_geburtsdatum.setText(_translate("ApprenticeManager", "TextLabel"))
        self.label_35.setText(_translate("ApprenticeManager", "Geschlecht:"))
        self.label_geschlecht.setText(_translate("ApprenticeManager", "TextLabel"))
        self.pushButton_lehrling_loeschen.setText(_translate("ApprenticeManager", "Lehrling löschen"))
        self.pushButton_stammdaten_bearbeiten.setText(_translate("ApprenticeManager", "Stammdaten bearbeiten"))
        self.apprentice_tabWidget.setTabText(self.apprentice_tabWidget.indexOf(self.stammdaten), _translate("ApprenticeManager", "Stammdaten"))
        self.apprentice_tabWidget.setTabText(self.apprentice_tabWidget.indexOf(self.tab_2), _translate("ApprenticeManager", "Schulungen"))
        self.pushButton_alle_lehrlinge.setText(_translate("ApprenticeManager", "Alle Lehrlinge"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApprenticeManager = QtWidgets.QDialog()
    ui = Ui_ApprenticeManager()
    ui.setupUi(ApprenticeManager)
    ApprenticeManager.show()
    sys.exit(app.exec_())
