# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Projekte\Knapp_Apprentice_Training\sub\learningcontent\LehrstoffSuchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lehrstoff_Suche(object):
    def setupUi(self, Lehrstoff_Suche):
        Lehrstoff_Suche.setObjectName("Lehrstoff_Suche")
        Lehrstoff_Suche.resize(713, 450)
        Lehrstoff_Suche.setMinimumSize(QtCore.QSize(713, 450))
        Lehrstoff_Suche.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Lehrstoff_Suche)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_Suchbegriff = QtWidgets.QLabel(Lehrstoff_Suche)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Suchbegriff.setFont(font)
        self.lbl_Suchbegriff.setObjectName("lbl_Suchbegriff")
        self.horizontalLayout_2.addWidget(self.lbl_Suchbegriff)
        self.le_Suchbegriff = QtWidgets.QLineEdit(Lehrstoff_Suche)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_Suchbegriff.setFont(font)
        self.le_Suchbegriff.setObjectName("le_Suchbegriff")
        self.horizontalLayout_2.addWidget(self.le_Suchbegriff)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tW_Lehrstoff_DB = QtWidgets.QTableWidget(Lehrstoff_Suche)
        self.tW_Lehrstoff_DB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tW_Lehrstoff_DB.setFont(font)
        self.tW_Lehrstoff_DB.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tW_Lehrstoff_DB.setAlternatingRowColors(True)
        self.tW_Lehrstoff_DB.setObjectName("tW_Lehrstoff_DB")
        self.tW_Lehrstoff_DB.setColumnCount(0)
        self.tW_Lehrstoff_DB.setRowCount(0)
        self.tW_Lehrstoff_DB.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.tW_Lehrstoff_DB)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(500)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_Suchen = QtWidgets.QPushButton(Lehrstoff_Suche)
        self.pB_Suchen.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Suchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Suchen.setIcon(icon)
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.horizontalLayout.addWidget(self.pB_Suchen)
        self.pB_Beenden = QtWidgets.QPushButton(Lehrstoff_Suche)
        self.pB_Beenden.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Beenden.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon1)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.horizontalLayout.addWidget(self.pB_Beenden)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Lehrstoff_Suche)
        QtCore.QMetaObject.connectSlotsByName(Lehrstoff_Suche)
        Lehrstoff_Suche.setTabOrder(self.le_Suchbegriff, self.pB_Suchen)
        Lehrstoff_Suche.setTabOrder(self.pB_Suchen, self.pB_Beenden)
        Lehrstoff_Suche.setTabOrder(self.pB_Beenden, self.tW_Lehrstoff_DB)

    def retranslateUi(self, Lehrstoff_Suche):
        _translate = QtCore.QCoreApplication.translate
        Lehrstoff_Suche.setWindowTitle(_translate("Lehrstoff_Suche", "Suche"))
        self.lbl_Suchbegriff.setText(_translate("Lehrstoff_Suche", "Suchen:"))
        self.pB_Suchen.setText(_translate("Lehrstoff_Suche", "Suchen"))
        self.pB_Beenden.setText(_translate("Lehrstoff_Suche", "Beenden"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lehrstoff_Suche = QtWidgets.QDialog()
    ui = Ui_Lehrstoff_Suche()
    ui.setupUi(Lehrstoff_Suche)
    Lehrstoff_Suche.show()
    sys.exit(app.exec_())
