# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gornicec\Downloads\V1.5\Knapp_Apprentice_Training\sub\specialmodules\spezial_suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 648)
        Dialog.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 91, 16))
        self.label.setObjectName("label")
        self.pB_BEENDEN = QtWidgets.QPushButton(Dialog)
        self.pB_BEENDEN.setGeometry(QtCore.QRect(968, 11, 93, 29))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\gornicec\\Downloads\\V1.5\\Knapp_Apprentice_Training\\sub\\specialmodules\\../../../_Symbole/Icons/computer/MSGBOX01.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_BEENDEN.setIcon(icon)
        self.pB_BEENDEN.setObjectName("pB_BEENDEN")
        self.le_suche = QtWidgets.QLineEdit(Dialog)
        self.le_suche.setGeometry(QtCore.QRect(150, 20, 251, 22))
        self.le_suche.setObjectName("le_suche")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 681, 581))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.btn_suchen = QtWidgets.QPushButton(Dialog)
        self.btn_suchen.setGeometry(QtCore.QRect(470, 20, 93, 28))
        self.btn_suchen.setObjectName("btn_suchen")
        self.btn_abbrechen = QtWidgets.QPushButton(Dialog)
        self.btn_abbrechen.setGeometry(QtCore.QRect(570, 20, 93, 28))
        self.btn_abbrechen.setObjectName("btn_abbrechen")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Spezialmodul"))
        self.pB_BEENDEN.setText(_translate("Dialog", "Beenden"))
        self.btn_suchen.setText(_translate("Dialog", "Suchen"))
        self.btn_abbrechen.setText(_translate("Dialog", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
