# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\Bemerkung.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 457)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.KW_l = QtWidgets.QLabel(Dialog)
        self.KW_l.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.KW_l.setObjectName("KW_l")
        self.horizontalLayout_2.addWidget(self.KW_l)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_generieren = QtWidgets.QPushButton(Dialog)
        self.pushButton_generieren.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_generieren.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/hammer_wrench_icon_135529.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_generieren.setIcon(icon)
        self.pushButton_generieren.setObjectName("pushButton_generieren")
        self.horizontalLayout.addWidget(self.pushButton_generieren)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.ss = QtWidgets.QWidget()
        self.ss.setObjectName("ss")
        self.lineEdit_1A = QtWidgets.QLineEdit(self.ss)
        self.lineEdit_1A.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_1A.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_1A.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_1A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_1A.setObjectName("lineEdit_1A")
        self.label_2 = QtWidgets.QLabel(self.ss)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ss)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_1B = QtWidgets.QLineEdit(self.ss)
        self.lineEdit_1B.setGeometry(QtCore.QRect(20, 170, 700, 80))
        self.lineEdit_1B.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_1B.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_1B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_1B.setObjectName("lineEdit_1B")
        self.tabWidget.addTab(self.ss, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_2B = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2B.setGeometry(QtCore.QRect(20, 170, 700, 80))
        self.lineEdit_2B.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_2B.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_2B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_2B.setObjectName("lineEdit_2B")
        self.lineEdit_2A = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2A.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_2A.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_2A.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_2A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_2A.setObjectName("lineEdit_2A")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_3B = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3B.setGeometry(QtCore.QRect(20, 170, 700, 80))
        self.lineEdit_3B.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_3B.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_3B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_3B.setObjectName("lineEdit_3B")
        self.lineEdit_3A = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3A.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_3A.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_3A.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_3A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_3A.setObjectName("lineEdit_3A")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_4B = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_4B.setGeometry(QtCore.QRect(20, 170, 700, 80))
        self.lineEdit_4B.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_4B.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_4B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_4B.setObjectName("lineEdit_4B")
        self.lineEdit_4A = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_4A.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_4A.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_4A.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_4A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_4A.setObjectName("lineEdit_4A")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.lineEdit_BS = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_BS.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_BS.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_BS.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_BS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_BS.setObjectName("lineEdit_BS")
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_24 = QtWidgets.QLabel(self.tab_9)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_Homeoffice = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_Homeoffice.setGeometry(QtCore.QRect(20, 40, 700, 80))
        self.lineEdit_Homeoffice.setMinimumSize(QtCore.QSize(700, 80))
        self.lineEdit_Homeoffice.setMaximumSize(QtCore.QSize(700, 80))
        self.lineEdit_Homeoffice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_Homeoffice.setObjectName("lineEdit_Homeoffice")
        self.tabWidget.addTab(self.tab_9, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_abbrechen = QtWidgets.QPushButton(Dialog)
        self.pushButton_abbrechen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abbrechen.setIcon(icon1)
        self.pushButton_abbrechen.setObjectName("pushButton_abbrechen")
        self.horizontalLayout_3.addWidget(self.pushButton_abbrechen)
        self.pushButton_Speichern = QtWidgets.QPushButton(Dialog)
        self.pushButton_Speichern.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/kat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Speichern.setIcon(icon2)
        self.pushButton_Speichern.setObjectName("pushButton_Speichern")
        self.horizontalLayout_3.addWidget(self.pushButton_Speichern)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "KW:"))
        self.KW_l.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_generieren.setText(_translate("Dialog", "Inhalt generieren"))
        self.label_2.setText(_translate("Dialog", "Gruppe 1A"))
        self.label_3.setText(_translate("Dialog", "Gruppe 1B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ss), _translate("Dialog", "Gruppe 1"))
        self.label_7.setText(_translate("Dialog", "Gruppe 2A"))
        self.label_9.setText(_translate("Dialog", "Gruppe 2B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Gruppe 2"))
        self.label_10.setText(_translate("Dialog", "Gruppe 3A"))
        self.label_11.setText(_translate("Dialog", "Gruppe 3B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Gruppe 3"))
        self.label_12.setText(_translate("Dialog", "Gruppe 4A"))
        self.label_13.setText(_translate("Dialog", "Gruppe 4B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Gruppe 4"))
        self.label_14.setText(_translate("Dialog", "Abwesenheit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "BS-Abwesend"))
        self.label_24.setText(_translate("Dialog", "Abwesenheit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Dialog", "Homeoffice"))
        self.pushButton_abbrechen.setText(_translate("Dialog", "Abbrechen"))
        self.pushButton_Speichern.setText(_translate("Dialog", "Speichern"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
