# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\hinzufuegen_Plan.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hinzufuegen(object):
    def setupUi(self, Hinzufuegen):
        Hinzufuegen.setObjectName("Hinzufuegen")
        Hinzufuegen.setEnabled(True)
        Hinzufuegen.resize(790, 856)
        Hinzufuegen.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Hinzufuegen)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Wochen_Tag = QtWidgets.QLabel(Hinzufuegen)
        self.Wochen_Tag.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Wochen_Tag.setObjectName("Wochen_Tag")
        self.horizontalLayout_12.addWidget(self.Wochen_Tag)
        self.label_9 = QtWidgets.QLabel(Hinzufuegen)
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(Hinzufuegen)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.label_10 = QtWidgets.QLabel(Hinzufuegen)
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(Hinzufuegen)
        self.label_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.timeEdit_von = QtWidgets.QTimeEdit(Hinzufuegen)
        self.timeEdit_von.setMinimumSize(QtCore.QSize(50, 0))
        self.timeEdit_von.setMaximumSize(QtCore.QSize(70, 16777215))
        self.timeEdit_von.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.timeEdit_von.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.timeEdit_von.setObjectName("timeEdit_von")
        self.horizontalLayout_12.addWidget(self.timeEdit_von)
        self.label_13 = QtWidgets.QLabel(Hinzufuegen)
        self.label_13.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.timeEdit_bis = QtWidgets.QTimeEdit(Hinzufuegen)
        self.timeEdit_bis.setMinimumSize(QtCore.QSize(50, 0))
        self.timeEdit_bis.setMaximumSize(QtCore.QSize(70, 16777215))
        self.timeEdit_bis.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.timeEdit_bis.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.timeEdit_bis.setObjectName("timeEdit_bis")
        self.horizontalLayout_12.addWidget(self.timeEdit_bis)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.Row = QtWidgets.QLabel(Hinzufuegen)
        self.Row.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Row.setObjectName("Row")
        self.verticalLayout.addWidget(self.Row)
        self.line = QtWidgets.QFrame(Hinzufuegen)
        self.line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Hinzufuegen)
        self.label_7.setMinimumSize(QtCore.QSize(155, 0))
        self.label_7.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.comboBox_Unterrichtsthema = QtWidgets.QComboBox(Hinzufuegen)
        self.comboBox_Unterrichtsthema.setEnabled(True)
        self.comboBox_Unterrichtsthema.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_Unterrichtsthema.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Unterrichtsthema.setEditable(True)
        self.comboBox_Unterrichtsthema.setObjectName("comboBox_Unterrichtsthema")
        self.comboBox_Unterrichtsthema.addItem("")
        self.comboBox_Unterrichtsthema.setItemText(0, "")
        self.horizontalLayout_4.addWidget(self.comboBox_Unterrichtsthema)
        self.label_15 = QtWidgets.QLabel(Hinzufuegen)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_15.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Hinzufuegen)
        self.label_6.setMinimumSize(QtCore.QSize(155, 0))
        self.label_6.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_Ausbilder = QtWidgets.QComboBox(Hinzufuegen)
        self.comboBox_Ausbilder.setEnabled(True)
        self.comboBox_Ausbilder.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_Ausbilder.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Ausbilder.setEditable(True)
        self.comboBox_Ausbilder.setObjectName("comboBox_Ausbilder")
        self.comboBox_Ausbilder.addItem("")
        self.comboBox_Ausbilder.setItemText(0, "")
        self.horizontalLayout_5.addWidget(self.comboBox_Ausbilder)
        self.le_vorname = QtWidgets.QLineEdit(Hinzufuegen)
        self.le_vorname.setEnabled(False)
        self.le_vorname.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_vorname.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.le_vorname.setObjectName("le_vorname")
        self.horizontalLayout_5.addWidget(self.le_vorname)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Hinzufuegen)
        self.label.setMinimumSize(QtCore.QSize(155, 0))
        self.label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_Raum = QtWidgets.QComboBox(Hinzufuegen)
        self.comboBox_Raum.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_Raum.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Raum.setEditable(False)
        self.comboBox_Raum.setObjectName("comboBox_Raum")
        self.comboBox_Raum.addItem("")
        self.comboBox_Raum.setItemText(0, "")
        self.horizontalLayout.addWidget(self.comboBox_Raum)
        self.le_raum = QtWidgets.QLineEdit(Hinzufuegen)
        self.le_raum.setEnabled(False)
        self.le_raum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_raum.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.le_raum.setObjectName("le_raum")
        self.horizontalLayout.addWidget(self.le_raum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(Hinzufuegen)
        self.line_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(Hinzufuegen)
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(Hinzufuegen)
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(Hinzufuegen)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 110))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 110))
        self.groupBox_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 219, 80))
        self.horizontalLayoutWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_1A = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_1A.setEnabled(False)
        self.checkBox_1A.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1A.setObjectName("checkBox_1A")
        self.verticalLayout_2.addWidget(self.checkBox_1A)
        self.checkBox_1B = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_1B.setEnabled(False)
        self.checkBox_1B.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1B.setObjectName("checkBox_1B")
        self.verticalLayout_2.addWidget(self.checkBox_1B)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_2A = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2A.setEnabled(False)
        self.checkBox_2A.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2A.setObjectName("checkBox_2A")
        self.verticalLayout_3.addWidget(self.checkBox_2A)
        self.checkBox_2B = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2B.setEnabled(False)
        self.checkBox_2B.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2B.setObjectName("checkBox_2B")
        self.verticalLayout_3.addWidget(self.checkBox_2B)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_3A = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_3A.setEnabled(False)
        self.checkBox_3A.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3A.setObjectName("checkBox_3A")
        self.verticalLayout_4.addWidget(self.checkBox_3A)
        self.checkBox_3B = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_3B.setEnabled(False)
        self.checkBox_3B.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3B.setObjectName("checkBox_3B")
        self.verticalLayout_4.addWidget(self.checkBox_3B)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_4A = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_4A.setEnabled(False)
        self.checkBox_4A.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4A.setObjectName("checkBox_4A")
        self.verticalLayout_5.addWidget(self.checkBox_4A)
        self.checkBox_4B = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_4B.setEnabled(False)
        self.checkBox_4B.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4B.setObjectName("checkBox_4B")
        self.verticalLayout_5.addWidget(self.checkBox_4B)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.checkBox_APP = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_APP.setGeometry(QtCore.QRect(50, 0, 60, 20))
        self.checkBox_APP.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_APP.setText("")
        self.checkBox_APP.setObjectName("checkBox_APP")
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Hinzufuegen)
        self.groupBox_3.setMinimumSize(QtCore.QSize(250, 110))
        self.groupBox_3.setMaximumSize(QtCore.QSize(250, 110))
        self.groupBox_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 219, 80))
        self.horizontalLayoutWidget_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_1A_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_1A_2.setEnabled(False)
        self.checkBox_1A_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1A_2.setObjectName("checkBox_1A_2")
        self.verticalLayout_7.addWidget(self.checkBox_1A_2)
        self.checkBox_1B_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_1B_2.setEnabled(False)
        self.checkBox_1B_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1B_2.setObjectName("checkBox_1B_2")
        self.verticalLayout_7.addWidget(self.checkBox_1B_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_2A_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_2A_2.setEnabled(False)
        self.checkBox_2A_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2A_2.setObjectName("checkBox_2A_2")
        self.verticalLayout_10.addWidget(self.checkBox_2A_2)
        self.checkBox_2B_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_2B_2.setEnabled(False)
        self.checkBox_2B_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2B_2.setObjectName("checkBox_2B_2")
        self.verticalLayout_10.addWidget(self.checkBox_2B_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_3A_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_3A_2.setEnabled(False)
        self.checkBox_3A_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3A_2.setObjectName("checkBox_3A_2")
        self.verticalLayout_11.addWidget(self.checkBox_3A_2)
        self.checkBox_3B_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_3B_2.setEnabled(False)
        self.checkBox_3B_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3B_2.setObjectName("checkBox_3B_2")
        self.verticalLayout_11.addWidget(self.checkBox_3B_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_4A_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_4A_2.setEnabled(False)
        self.checkBox_4A_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4A_2.setObjectName("checkBox_4A_2")
        self.verticalLayout_12.addWidget(self.checkBox_4A_2)
        self.checkBox_4B_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_4B_2.setEnabled(False)
        self.checkBox_4B_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4B_2.setObjectName("checkBox_4B_2")
        self.verticalLayout_12.addWidget(self.checkBox_4B_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.checkBox_ME = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_ME.setGeometry(QtCore.QRect(40, 0, 30, 20))
        self.checkBox_ME.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_ME.setText("")
        self.checkBox_ME.setObjectName("checkBox_ME")
        self.horizontalLayout_18.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Hinzufuegen)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 110))
        self.groupBox_4.setMaximumSize(QtCore.QSize(250, 110))
        self.groupBox_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 219, 80))
        self.horizontalLayoutWidget_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_1A_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_1A_3.setEnabled(False)
        self.checkBox_1A_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1A_3.setObjectName("checkBox_1A_3")
        self.verticalLayout_13.addWidget(self.checkBox_1A_3)
        self.checkBox_1B_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_1B_3.setEnabled(False)
        self.checkBox_1B_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_1B_3.setObjectName("checkBox_1B_3")
        self.verticalLayout_13.addWidget(self.checkBox_1B_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.checkBox_2A_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_2A_3.setEnabled(False)
        self.checkBox_2A_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2A_3.setObjectName("checkBox_2A_3")
        self.verticalLayout_14.addWidget(self.checkBox_2A_3)
        self.checkBox_2B_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_2B_3.setEnabled(False)
        self.checkBox_2B_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_2B_3.setObjectName("checkBox_2B_3")
        self.verticalLayout_14.addWidget(self.checkBox_2B_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.checkBox_3A_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_3A_3.setEnabled(False)
        self.checkBox_3A_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3A_3.setObjectName("checkBox_3A_3")
        self.verticalLayout_15.addWidget(self.checkBox_3A_3)
        self.checkBox_3B_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_3B_3.setEnabled(False)
        self.checkBox_3B_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_3B_3.setObjectName("checkBox_3B_3")
        self.verticalLayout_15.addWidget(self.checkBox_3B_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.checkBox_4A_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_4A_3.setEnabled(False)
        self.checkBox_4A_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4A_3.setObjectName("checkBox_4A_3")
        self.verticalLayout_16.addWidget(self.checkBox_4A_3)
        self.checkBox_4B_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_4B_3.setEnabled(False)
        self.checkBox_4B_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_4B_3.setObjectName("checkBox_4B_3")
        self.verticalLayout_16.addWidget(self.checkBox_4B_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_16)
        self.checkBox_MB = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_MB.setGeometry(QtCore.QRect(40, 0, 30, 20))
        self.checkBox_MB.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.checkBox_MB.setText("")
        self.checkBox_MB.setObjectName("checkBox_MB")
        self.horizontalLayout_18.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(Hinzufuegen)
        self.line_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(Hinzufuegen)
        self.label_4.setMinimumSize(QtCore.QSize(155, 0))
        self.label_4.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.pushButton_einzelne_lehrlinge = QtWidgets.QPushButton(Hinzufuegen)
        self.pushButton_einzelne_lehrlinge.setMinimumSize(QtCore.QSize(355, 0))
        self.pushButton_einzelne_lehrlinge.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_einzelne_lehrlinge.setObjectName("pushButton_einzelne_lehrlinge")
        self.horizontalLayout_16.addWidget(self.pushButton_einzelne_lehrlinge)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_3 = QtWidgets.QLabel(Hinzufuegen)
        self.label_3.setMinimumSize(QtCore.QSize(155, 20))
        self.label_3.setMaximumSize(QtCore.QSize(155, 20))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3)
        self.label_16 = QtWidgets.QLabel(Hinzufuegen)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.le_information = QtWidgets.QLineEdit(Hinzufuegen)
        self.le_information.setMinimumSize(QtCore.QSize(0, 50))
        self.le_information.setMaximumSize(QtCore.QSize(16777215, 100))
        self.le_information.setObjectName("le_information")
        self.horizontalLayout_13.addWidget(self.le_information)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.groupBox = QtWidgets.QGroupBox(Hinzufuegen)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 125))
        self.groupBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 658, 103))
        self.verticalLayoutWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 40))
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.comboBox_Thema1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_Thema1.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_Thema1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Thema1.setEditable(False)
        self.comboBox_Thema1.setObjectName("comboBox_Thema1")
        self.comboBox_Thema1.addItem("")
        self.comboBox_Thema1.setItemText(0, "")
        self.horizontalLayout_6.addWidget(self.comboBox_Thema1)
        self.sb_Thema1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema1.setEnabled(False)
        self.sb_Thema1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sb_Thema1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.sb_Thema1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_Thema1.setObjectName("sb_Thema1")
        self.horizontalLayout_6.addWidget(self.sb_Thema1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setMaximumSize(QtCore.QSize(120, 40))
        self.label_18.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.comboBox_Thema2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_Thema2.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_Thema2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Thema2.setEditable(False)
        self.comboBox_Thema2.setObjectName("comboBox_Thema2")
        self.comboBox_Thema2.addItem("")
        self.comboBox_Thema2.setItemText(0, "")
        self.horizontalLayout_7.addWidget(self.comboBox_Thema2)
        self.sb_Thema2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema2.setEnabled(False)
        self.sb_Thema2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sb_Thema2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.sb_Thema2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_Thema2.setObjectName("sb_Thema2")
        self.horizontalLayout_7.addWidget(self.sb_Thema2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(120, 0))
        self.label_17.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_17.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.comboBox_Thema3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_Thema3.setEnabled(True)
        self.comboBox_Thema3.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox_Thema3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_Thema3.setEditable(False)
        self.comboBox_Thema3.setObjectName("comboBox_Thema3")
        self.comboBox_Thema3.addItem("")
        self.comboBox_Thema3.setItemText(0, "")
        self.horizontalLayout_8.addWidget(self.comboBox_Thema3)
        self.sb_Thema3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sb_Thema3.setEnabled(False)
        self.sb_Thema3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sb_Thema3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.sb_Thema3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_Thema3.setObjectName("sb_Thema3")
        self.horizontalLayout_8.addWidget(self.sb_Thema3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(Hinzufuegen)
        self.label_19.setMinimumSize(QtCore.QSize(520, 0))
        self.label_19.setMaximumSize(QtCore.QSize(100, 10))
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.gesamt_stunden = QtWidgets.QLineEdit(Hinzufuegen)
        self.gesamt_stunden.setEnabled(False)
        self.gesamt_stunden.setMaximumSize(QtCore.QSize(30, 16777215))
        self.gesamt_stunden.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.gesamt_stunden.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gesamt_stunden.setObjectName("gesamt_stunden")
        self.horizontalLayout_10.addWidget(self.gesamt_stunden)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(Hinzufuegen)
        self.label_12.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.te_vorschau = QtWidgets.QTableWidget(Hinzufuegen)
        self.te_vorschau.setMinimumSize(QtCore.QSize(0, 130))
        self.te_vorschau.setTabletTracking(False)
        self.te_vorschau.setFocusPolicy(QtCore.Qt.NoFocus)
        self.te_vorschau.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.te_vorschau.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.te_vorschau.setAutoFillBackground(True)
        self.te_vorschau.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.te_vorschau.setFrameShape(QtWidgets.QFrame.Box)
        self.te_vorschau.setFrameShadow(QtWidgets.QFrame.Plain)
        self.te_vorschau.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.te_vorschau.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.te_vorschau.setTextElideMode(QtCore.Qt.ElideRight)
        self.te_vorschau.setShowGrid(True)
        self.te_vorschau.setGridStyle(QtCore.Qt.NoPen)
        self.te_vorschau.setObjectName("te_vorschau")
        self.te_vorschau.setColumnCount(1)
        self.te_vorschau.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.te_vorschau.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.te_vorschau.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.te_vorschau.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.te_vorschau.setItem(2, 0, item)
        self.verticalLayout_9.addWidget(self.te_vorschau)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_abbrechen = QtWidgets.QPushButton(Hinzufuegen)
        self.pushButton_abbrechen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abbrechen.setIcon(icon)
        self.pushButton_abbrechen.setObjectName("pushButton_abbrechen")
        self.horizontalLayout_2.addWidget(self.pushButton_abbrechen)
        self.pushButton_loeschen = QtWidgets.QPushButton(Hinzufuegen)
        self.pushButton_loeschen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/seo-social-web-network-internet_262_icon-icons.com_61518.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loeschen.setIcon(icon1)
        self.pushButton_loeschen.setObjectName("pushButton_loeschen")
        self.horizontalLayout_2.addWidget(self.pushButton_loeschen)
        self.pushButton_Anwesenheit = QtWidgets.QPushButton(Hinzufuegen)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Anwesenheit.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/MISC28.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Anwesenheit.setIcon(icon2)
        self.pushButton_Anwesenheit.setObjectName("pushButton_Anwesenheit")
        self.horizontalLayout_2.addWidget(self.pushButton_Anwesenheit)
        self.pushButton_hinzufuegen = QtWidgets.QPushButton(Hinzufuegen)
        self.pushButton_hinzufuegen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/add_insert_new_plus_icon_148990.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hinzufuegen.setIcon(icon3)
        self.pushButton_hinzufuegen.setObjectName("pushButton_hinzufuegen")
        self.horizontalLayout_2.addWidget(self.pushButton_hinzufuegen)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Hinzufuegen)
        QtCore.QMetaObject.connectSlotsByName(Hinzufuegen)

    def retranslateUi(self, Hinzufuegen):
        _translate = QtCore.QCoreApplication.translate
        Hinzufuegen.setWindowTitle(_translate("Hinzufuegen", "Stunde hinzf./Bearbeiten"))
        self.Wochen_Tag.setText(_translate("Hinzufuegen", "TextLabel"))
        self.label_2.setText(_translate("Hinzufuegen", "UNTERRICHT"))
        self.label_11.setText(_translate("Hinzufuegen", "von"))
        self.label_13.setText(_translate("Hinzufuegen", "bis"))
        self.Row.setText(_translate("Hinzufuegen", "<html><head/><body><p><span style=\" font-size:6pt;\">TextLabel</span></p></body></html>"))
        self.label_7.setText(_translate("Hinzufuegen", "Unterrichtsthema"))
        self.label_6.setText(_translate("Hinzufuegen", "Ausbilder"))
        self.label.setText(_translate("Hinzufuegen", "Raum"))
        self.label_5.setText(_translate("Hinzufuegen", "Gruppen/LJ"))
        self.groupBox_2.setTitle(_translate("Hinzufuegen", "APP"))
        self.checkBox_1A.setText(_translate("Hinzufuegen", "1A"))
        self.checkBox_1B.setText(_translate("Hinzufuegen", "1B"))
        self.checkBox_2A.setText(_translate("Hinzufuegen", "2A"))
        self.checkBox_2B.setText(_translate("Hinzufuegen", "2B"))
        self.checkBox_3A.setText(_translate("Hinzufuegen", "3A"))
        self.checkBox_3B.setText(_translate("Hinzufuegen", "3B"))
        self.checkBox_4A.setText(_translate("Hinzufuegen", "4A"))
        self.checkBox_4B.setText(_translate("Hinzufuegen", "4B"))
        self.groupBox_3.setTitle(_translate("Hinzufuegen", "ME"))
        self.checkBox_1A_2.setText(_translate("Hinzufuegen", "1A"))
        self.checkBox_1B_2.setText(_translate("Hinzufuegen", "1B"))
        self.checkBox_2A_2.setText(_translate("Hinzufuegen", "2A"))
        self.checkBox_2B_2.setText(_translate("Hinzufuegen", "2B"))
        self.checkBox_3A_2.setText(_translate("Hinzufuegen", "3A"))
        self.checkBox_3B_2.setText(_translate("Hinzufuegen", "3B"))
        self.checkBox_4A_2.setText(_translate("Hinzufuegen", "4A"))
        self.checkBox_4B_2.setText(_translate("Hinzufuegen", "4B"))
        self.groupBox_4.setTitle(_translate("Hinzufuegen", "MB"))
        self.checkBox_1A_3.setText(_translate("Hinzufuegen", "1A"))
        self.checkBox_1B_3.setText(_translate("Hinzufuegen", "1B"))
        self.checkBox_2A_3.setText(_translate("Hinzufuegen", "2A"))
        self.checkBox_2B_3.setText(_translate("Hinzufuegen", "2B"))
        self.checkBox_3A_3.setText(_translate("Hinzufuegen", "3A"))
        self.checkBox_3B_3.setText(_translate("Hinzufuegen", "3B"))
        self.checkBox_4A_3.setText(_translate("Hinzufuegen", "4A"))
        self.checkBox_4B_3.setText(_translate("Hinzufuegen", "4B"))
        self.label_4.setText(_translate("Hinzufuegen", "Einzelne Lehrlinge"))
        self.pushButton_einzelne_lehrlinge.setText(_translate("Hinzufuegen", "Auswählen..."))
        self.label_3.setText(_translate("Hinzufuegen", "Sonstige Information"))
        self.groupBox.setTitle(_translate("Hinzufuegen", "Ausbildungstheman                                                                                                   Stunden"))
        self.label_14.setText(_translate("Hinzufuegen", "Thema 1"))
        self.sb_Thema1.setText(_translate("Hinzufuegen", "0"))
        self.label_18.setText(_translate("Hinzufuegen", "Thema 2"))
        self.sb_Thema2.setText(_translate("Hinzufuegen", "0"))
        self.label_17.setText(_translate("Hinzufuegen", "Thema 3"))
        self.sb_Thema3.setText(_translate("Hinzufuegen", "0"))
        self.label_12.setText(_translate("Hinzufuegen", "Vorschau"))
        __sortingEnabled = self.te_vorschau.isSortingEnabled()
        self.te_vorschau.setSortingEnabled(False)
        self.te_vorschau.setSortingEnabled(__sortingEnabled)
        self.pushButton_abbrechen.setText(_translate("Hinzufuegen", "Abbrechen"))
        self.pushButton_loeschen.setText(_translate("Hinzufuegen", "Löschen"))
        self.pushButton_Anwesenheit.setText(_translate("Hinzufuegen", "Anwesenheit"))
        self.pushButton_hinzufuegen.setText(_translate("Hinzufuegen", "Speichern"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Hinzufuegen = QtWidgets.QDialog()
    ui = Ui_Hinzufuegen()
    ui.setupUi(Hinzufuegen)
    Hinzufuegen.show()
    sys.exit(app.exec_())
