# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Aktuelle\04022021\Knapp_Apprentice_Training\sub\specialmodules\spezial_suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 480)
        Dialog.setMinimumSize(QtCore.QSize(570, 480))
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.le_suche = QtWidgets.QLineEdit(self.groupBox)
        self.le_suche.setGeometry(QtCore.QRect(160, 40, 251, 22))
        self.le_suche.setObjectName("le_suche")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_suchen = QtWidgets.QPushButton(self.groupBox)
        self.btn_suchen.setGeometry(QtCore.QRect(160, 80, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_suchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_suchen.setIcon(icon)
        self.btn_suchen.setObjectName("btn_suchen")
        self.btn_abbrechen = QtWidgets.QPushButton(self.groupBox)
        self.btn_abbrechen.setGeometry(QtCore.QRect(270, 80, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_abbrechen.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abbrechen.setIcon(icon1)
        self.btn_abbrechen.setObjectName("btn_abbrechen")
        self.verticalLayout.addWidget(self.groupBox)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Spezialmodule - Suche"))
        self.groupBox.setTitle(_translate("Dialog", "Suche"))
        self.label.setText(_translate("Dialog", "Spezialmodul"))
        self.btn_suchen.setText(_translate("Dialog", "Suchen"))
        self.btn_abbrechen.setText(_translate("Dialog", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
