# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Koele - Unterricht\Quantschnig IT\Pyhton\Beispiele\Knapp_Apprentice_Training\sub\rooms\Raeume_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 664)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pB_Suchen = QtWidgets.QPushButton(Dialog)
        self.pB_Suchen.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Suchen.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.gridLayout.addWidget(self.pB_Suchen, 3, 0, 1, 1)
        self.lb_Room = QtWidgets.QLabel(Dialog)
        self.lb_Room.setMinimumSize(QtCore.QSize(120, 0))
        self.lb_Room.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lb_Room.setObjectName("lb_Room")
        self.gridLayout.addWidget(self.lb_Room, 0, 0, 1, 1)
        self.leRaumNr = QtWidgets.QLineEdit(Dialog)
        self.leRaumNr.setObjectName("leRaumNr")
        self.gridLayout.addWidget(self.leRaumNr, 0, 3, 1, 1)
        self.pB_Beenden = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Beenden.sizePolicy().hasHeightForWidth())
        self.pB_Beenden.setSizePolicy(sizePolicy)
        self.pB_Beenden.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Beenden.setMaximumSize(QtCore.QSize(120, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Koele - Unterricht\\Quantschnig IT\\Pyhton\\Beispiele\\Knapp_Apprentice_Training\\sub\\rooms\\../../UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.gridLayout.addWidget(self.pB_Beenden, 3, 3, 1, 1)
        self.leRaeume = QtWidgets.QLineEdit(Dialog)
        self.leRaeume.setObjectName("leRaeume")
        self.gridLayout.addWidget(self.leRaeume, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leGebaeude = QtWidgets.QLineEdit(Dialog)
        self.leGebaeude.setObjectName("leGebaeude")
        self.gridLayout.addWidget(self.leGebaeude, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.tb_Raeume = QtWidgets.QTableWidget(Dialog)
        self.tb_Raeume.setObjectName("tb_Raeume")
        self.tb_Raeume.setColumnCount(0)
        self.tb_Raeume.setRowCount(0)
        self.gridLayout.addWidget(self.tb_Raeume, 2, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pB_Suchen.setText(_translate("Dialog", "Suchen"))
        self.lb_Room.setText(_translate("Dialog", "Raum"))
        self.pB_Beenden.setText(_translate("Dialog", "Beenden"))
        self.label_2.setText(_translate("Dialog", "Gebäude"))
        self.label.setText(_translate("Dialog", "Raum-Nr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
