# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\projects\Python\V1.7\Knapp_Apprentice_Training\sub\field\Fachrichtungen_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suche_Dialog(object):
    def setupUi(self, Suche_Dialog):
        Suche_Dialog.setObjectName("Suche_Dialog")
        Suche_Dialog.resize(797, 703)
        Suche_Dialog.setMinimumSize(QtCore.QSize(797, 703))
        Suche_Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Suche_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gbSuche = QtWidgets.QGroupBox(Suche_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbSuche.sizePolicy().hasHeightForWidth())
        self.gbSuche.setSizePolicy(sizePolicy)
        self.gbSuche.setMinimumSize(QtCore.QSize(777, 111))
        self.gbSuche.setMaximumSize(QtCore.QSize(777, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbSuche.setFont(font)
        self.gbSuche.setObjectName("gbSuche")
        self.btSuchen = QtWidgets.QPushButton(self.gbSuche)
        self.btSuchen.setGeometry(QtCore.QRect(550, 45, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btSuchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\projects\\Python\\V1.7\\Knapp_Apprentice_Training\\sub\\field\\../../_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSuchen.setIcon(icon)
        self.btSuchen.setObjectName("btSuchen")
        self.pB_BEENDEN = QtWidgets.QPushButton(self.gbSuche)
        self.pB_BEENDEN.setGeometry(QtCore.QRect(660, 45, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_BEENDEN.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\projects\\Python\\V1.7\\Knapp_Apprentice_Training\\sub\\field\\../../_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_BEENDEN.setIcon(icon1)
        self.pB_BEENDEN.setObjectName("pB_BEENDEN")
        self.lbSuche = QtWidgets.QLabel(self.gbSuche)
        self.lbSuche.setGeometry(QtCore.QRect(60, 52, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbSuche.setFont(font)
        self.lbSuche.setObjectName("lbSuche")
        self.leSuche = QtWidgets.QLineEdit(self.gbSuche)
        self.leSuche.setGeometry(QtCore.QRect(130, 49, 371, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leSuche.setFont(font)
        self.leSuche.setObjectName("leSuche")
        self.gridLayout.addWidget(self.gbSuche, 0, 0, 1, 1)
        self.twAnzeige_suche = QtWidgets.QTableWidget(Suche_Dialog)
        self.twAnzeige_suche.setMinimumSize(QtCore.QSize(777, 565))
        self.twAnzeige_suche.setMaximumSize(QtCore.QSize(77777, 77777))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.twAnzeige_suche.setFont(font)
        self.twAnzeige_suche.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twAnzeige_suche.setAlternatingRowColors(True)
        self.twAnzeige_suche.setObjectName("twAnzeige_suche")
        self.twAnzeige_suche.setColumnCount(0)
        self.twAnzeige_suche.setRowCount(0)
        self.twAnzeige_suche.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.twAnzeige_suche, 1, 0, 1, 1)

        self.retranslateUi(Suche_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Suche_Dialog)

    def retranslateUi(self, Suche_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Suche_Dialog.setWindowTitle(_translate("Suche_Dialog", "Suche"))
        self.gbSuche.setTitle(_translate("Suche_Dialog", "Suche Fachrichtung:"))
        self.btSuchen.setText(_translate("Suche_Dialog", "Suchen"))
        self.pB_BEENDEN.setText(_translate("Suche_Dialog", "Beenden"))
        self.lbSuche.setText(_translate("Suche_Dialog", "Suche:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Suche_Dialog = QtWidgets.QDialog()
    ui = Ui_Suche_Dialog()
    ui.setupUi(Suche_Dialog)
    Suche_Dialog.show()
    sys.exit(app.exec_())
