# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Knapp_Apprentice_Training\sub\ausbildungsthemen\Unterrichtsthemen_suchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Unterrichtsthemen_suchen(object):
    def setupUi(self, Unterrichtsthemen_suchen):
        Unterrichtsthemen_suchen.setObjectName("Unterrichtsthemen_suchen")
        Unterrichtsthemen_suchen.resize(875, 479)
        font = QtGui.QFont()
        font.setPointSize(10)
        Unterrichtsthemen_suchen.setFont(font)
        Unterrichtsthemen_suchen.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Unterrichtsthemen_suchen)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Unterrichtsthemen_suchen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(853, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_suche = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_suche.setGeometry(QtCore.QRect(110, 30, 731, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_suche.setFont(font)
        self.le_suche.setObjectName("le_suche")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(320, 60, 214, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_suchen = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_suchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_suchen.setIcon(icon)
        self.pb_suchen.setObjectName("pb_suchen")
        self.horizontalLayout.addWidget(self.pb_suchen)
        self.pb_abbrechen = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_abbrechen.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_abbrechen.setIcon(icon1)
        self.pb_abbrechen.setObjectName("pb_abbrechen")
        self.horizontalLayout.addWidget(self.pb_abbrechen)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tw_suchen = QtWidgets.QTableWidget(Unterrichtsthemen_suchen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_suchen.sizePolicy().hasHeightForWidth())
        self.tw_suchen.setSizePolicy(sizePolicy)
        self.tw_suchen.setMinimumSize(QtCore.QSize(851, 311))
        self.tw_suchen.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_suchen.setAlternatingRowColors(True)
        self.tw_suchen.setObjectName("tw_suchen")
        self.tw_suchen.setColumnCount(0)
        self.tw_suchen.setRowCount(0)
        self.tw_suchen.verticalHeader().setVisible(False)
        self.tw_suchen.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.tw_suchen, 1, 0, 1, 1)
        self.l_info = QtWidgets.QLabel(Unterrichtsthemen_suchen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_info.sizePolicy().hasHeightForWidth())
        self.l_info.setSizePolicy(sizePolicy)
        self.l_info.setMinimumSize(QtCore.QSize(851, 31))
        self.l_info.setText("")
        self.l_info.setObjectName("l_info")
        self.gridLayout.addWidget(self.l_info, 2, 0, 1, 1)

        self.retranslateUi(Unterrichtsthemen_suchen)
        QtCore.QMetaObject.connectSlotsByName(Unterrichtsthemen_suchen)

    def retranslateUi(self, Unterrichtsthemen_suchen):
        _translate = QtCore.QCoreApplication.translate
        Unterrichtsthemen_suchen.setWindowTitle(_translate("Unterrichtsthemen_suchen", "Suchen"))
        self.groupBox_2.setTitle(_translate("Unterrichtsthemen_suchen", "Suche nach"))
        self.label_2.setText(_translate("Unterrichtsthemen_suchen", "Suchebgriff:"))
        self.pb_suchen.setText(_translate("Unterrichtsthemen_suchen", "Suchen"))
        self.pb_abbrechen.setText(_translate("Unterrichtsthemen_suchen", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Unterrichtsthemen_suchen = QtWidgets.QDialog()
    ui = Ui_Unterrichtsthemen_suchen()
    ui.setupUi(Unterrichtsthemen_suchen)
    Unterrichtsthemen_suchen.show()
    sys.exit(app.exec_())
