# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Koele - Unterricht\Quantschnig IT\Pyhton\Beispiele\Knapp_Apprentice_Training\sub\rooms\Raeume_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 619)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tb_Raeume = QtWidgets.QTableWidget(Dialog)
        self.tb_Raeume.setObjectName("tb_Raeume")
        self.tb_Raeume.setColumnCount(0)
        self.tb_Raeume.setRowCount(0)
        self.gridLayout.addWidget(self.tb_Raeume, 6, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 32))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pB_Beenden = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Beenden.sizePolicy().hasHeightForWidth())
        self.pB_Beenden.setSizePolicy(sizePolicy)
        self.pB_Beenden.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Beenden.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Beenden.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.gridLayout_2.addWidget(self.pB_Beenden, 0, 2, 1, 1)
        self.pB_Suchen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pB_Suchen.setMinimumSize(QtCore.QSize(120, 0))
        self.pB_Suchen.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Suchen.setFont(font)
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.gridLayout_2.addWidget(self.pB_Suchen, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 0, 1, 3)
        self.lb_Room = QtWidgets.QLabel(Dialog)
        self.lb_Room.setMinimumSize(QtCore.QSize(120, 0))
        self.lb_Room.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_Room.setFont(font)
        self.lb_Room.setObjectName("lb_Room")
        self.gridLayout.addWidget(self.lb_Room, 1, 0, 1, 1)
        self.leRaeume = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leRaeume.sizePolicy().hasHeightForWidth())
        self.leRaeume.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leRaeume.setFont(font)
        self.leRaeume.setObjectName("leRaeume")
        self.gridLayout.addWidget(self.leRaeume, 1, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.leRaeume, self.tb_Raeume)
        Dialog.setTabOrder(self.tb_Raeume, self.pB_Suchen)
        Dialog.setTabOrder(self.pB_Suchen, self.pB_Beenden)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Suche"))
        self.pB_Beenden.setText(_translate("Dialog", "Beenden"))
        self.pB_Suchen.setText(_translate("Dialog", "Suchen"))
        self.lb_Room.setText(_translate("Dialog", "Suchbegriff"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
