# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\projects\Python\V1.6\Knapp_Apprentice_Training\sub\mainwindow\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 467)
        MainWindow.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 26px;\n"
"height:26px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(_Symbole/UsedSymbols/dropdown.png);\n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-width: 2px;\n"
"    cursor: pointer;\n"
"background: rgb(180,180,180)\n"
"}\n"
"QPushButton:focus {\n"
"    border-width: 2px;\n"
"background: rgb(180,180,180)\n"
"}\n"
"QPushButton{\n"
"padding: 2px 7px;\n"
"border-color: black;\n"
"background-color: #FFFFFF;\n"
"border-radius:4px;\n"
"}\n"
"QMainWindow{\n"
"background-color:rgb(216,216,216) /*qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(216, 216, 216, 255), stop:1 rgba(162, 162, 162, 255))*/\n"
"}\n"
"QTabWidget::pane {\n"
"    border: 1px solid black;\n"
"    background: none;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid black;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: silver;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_INFO = QtWidgets.QLabel(self.centralwidget)
        self.lab_INFO.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lab_INFO.setObjectName("lab_INFO")
        self.gridLayout.addWidget(self.lab_INFO, 8, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"/*background-color: rgb(240,240,240)*/\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("")
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_lehrlinge = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_lehrlinge.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_lehrlinge.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/MISC28.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_lehrlinge.setIcon(icon)
        self.pushButton_lehrlinge.setObjectName("pushButton_lehrlinge")
        self.horizontalLayout_3.addWidget(self.pushButton_lehrlinge)
        self.pushButton_ausbilder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_ausbilder.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_ausbilder.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/trainer.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ausbilder.setIcon(icon1)
        self.pushButton_ausbilder.setObjectName("pushButton_ausbilder")
        self.horizontalLayout_3.addWidget(self.pushButton_ausbilder)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Unterrichtsthemen = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Unterrichtsthemen.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Unterrichtsthemen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/coordinated_assessment_documents_report_icon_148377.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Unterrichtsthemen.setIcon(icon2)
        self.pushButton_Unterrichtsthemen.setObjectName("pushButton_Unterrichtsthemen")
        self.horizontalLayout_4.addWidget(self.pushButton_Unterrichtsthemen)
        self.pushButton_raeume = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_raeume.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_raeume.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/place.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_raeume.setIcon(icon3)
        self.pushButton_raeume.setObjectName("pushButton_raeume")
        self.horizontalLayout_4.addWidget(self.pushButton_raeume)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_lehrberufe = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_lehrberufe.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_lehrberufe.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/training.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_lehrberufe.setIcon(icon4)
        self.pushButton_lehrberufe.setObjectName("pushButton_lehrberufe")
        self.horizontalLayout_2.addWidget(self.pushButton_lehrberufe)
        self.pushButton_spezialmodule = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_spezialmodule.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_spezialmodule.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_spezialmodule.setIcon(icon5)
        self.pushButton_spezialmodule.setObjectName("pushButton_spezialmodule")
        self.horizontalLayout_2.addWidget(self.pushButton_spezialmodule)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_LAP_Themenkatalog = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_LAP_Themenkatalog.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_LAP_Themenkatalog.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.pushButton_LAP_Themenkatalog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/2020-12-01 14_02_39-WIKA_OO1.jpg (590×182).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LAP_Themenkatalog.setIcon(icon6)
        self.pushButton_LAP_Themenkatalog.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_LAP_Themenkatalog.setObjectName("pushButton_LAP_Themenkatalog")
        self.horizontalLayout_6.addWidget(self.pushButton_LAP_Themenkatalog)
        self.pushButton_lehrstoff = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_lehrstoff.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_lehrstoff.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/MISC100.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_lehrstoff.setIcon(icon7)
        self.pushButton_lehrstoff.setObjectName("pushButton_lehrstoff")
        self.horizontalLayout_6.addWidget(self.pushButton_lehrstoff)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_Fachabteilungen = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Fachabteilungen.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Fachabteilungen.setObjectName("pushButton_Fachabteilungen")
        self.horizontalLayout_11.addWidget(self.pushButton_Fachabteilungen)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setStyleSheet("background: none;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/data.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("")
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 132))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_Wochen_U = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Wochen_U.setMinimumSize(QtCore.QSize(0, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/education_cap_icon_157723.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Wochen_U.setIcon(icon9)
        self.pushButton_Wochen_U.setObjectName("pushButton_Wochen_U")
        self.horizontalLayout_5.addWidget(self.pushButton_Wochen_U)
        self.pushButton_Lehrlingseinteilungtabelle = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Lehrlingseinteilungtabelle.setMinimumSize(QtCore.QSize(0, 30))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/table-grid_icon-icons.com_73384.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Lehrlingseinteilungtabelle.setIcon(icon10)
        self.pushButton_Lehrlingseinteilungtabelle.setObjectName("pushButton_Lehrlingseinteilungtabelle")
        self.horizontalLayout_5.addWidget(self.pushButton_Lehrlingseinteilungtabelle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_Berufsschulzeiten = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Berufsschulzeiten.setMinimumSize(QtCore.QSize(0, 30))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/school_bell_icon_175715.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Berufsschulzeiten.setIcon(icon11)
        self.pushButton_Berufsschulzeiten.setObjectName("pushButton_Berufsschulzeiten")
        self.horizontalLayout_7.addWidget(self.pushButton_Berufsschulzeiten)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("background: none;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("background: none;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("background: none;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/share_analytics.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon12, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setStyleSheet("")
        self.tab_5.setObjectName("tab_5")
        self.pushButton_Wochen_U_A = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_Wochen_U_A.setGeometry(QtCore.QRect(10, 10, 281, 30))
        self.pushButton_Wochen_U_A.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Wochen_U_A.setIcon(icon9)
        self.pushButton_Wochen_U_A.setObjectName("pushButton_Wochen_U_A")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("_Symbole/Icons/misc/assessment.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon13, "")
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 2, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background: none;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_abmelden = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_abmelden.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_abmelden.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: #DDDDDD;")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("_Symbole/Icons/computer/log_out.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abmelden.setIcon(icon14)
        self.pushButton_abmelden.setObjectName("pushButton_abmelden")
        self.gridLayout.addWidget(self.pushButton_abmelden, 7, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/Knapp_Logo.png"))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:none;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_eingeloggt_als = QtWidgets.QLabel(self.centralwidget)
        self.label_eingeloggt_als.setMaximumSize(QtCore.QSize(16777215, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_eingeloggt_als.setFont(font)
        self.label_eingeloggt_als.setStyleSheet("background:none;")
        self.label_eingeloggt_als.setObjectName("label_eingeloggt_als")
        self.gridLayout.addWidget(self.label_eingeloggt_als, 0, 3, 1, 1)
        self.pushButton_passwort = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_passwort.setFont(font)
        self.pushButton_passwort.setObjectName("pushButton_passwort")
        self.gridLayout.addWidget(self.pushButton_passwort, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Knapp Apprentice Training"))
        self.lab_INFO.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_lehrlinge.setText(_translate("MainWindow", "Lehrlinge"))
        self.pushButton_ausbilder.setText(_translate("MainWindow", "Ausbilder"))
        self.pushButton_Unterrichtsthemen.setText(_translate("MainWindow", "Unterrichtsthemen"))
        self.pushButton_raeume.setText(_translate("MainWindow", "Räume"))
        self.pushButton_lehrberufe.setText(_translate("MainWindow", "Fachrichtungen"))
        self.pushButton_spezialmodule.setText(_translate("MainWindow", "Spezialmodule"))
        self.pushButton_LAP_Themenkatalog.setText(_translate("MainWindow", "LAP-Themenkatalog"))
        self.pushButton_lehrstoff.setText(_translate("MainWindow", "Lehrstoff"))
        self.pushButton_Fachabteilungen.setText(_translate("MainWindow", "Fachabteilungen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Stammdaten"))
        self.pushButton_Wochen_U.setText(_translate("MainWindow", "Wochen-Unterricht"))
        self.pushButton_Lehrlingseinteilungtabelle.setText(_translate("MainWindow", "Lehrlingseinteilungtabelle"))
        self.pushButton_Berufsschulzeiten.setText(_translate("MainWindow", "Berufsschulzeiten"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Bewegungsdaten"))
        self.pushButton_Wochen_U_A.setText(_translate("MainWindow", "Wochen-Unterricht-Auswertung"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Auswertung"))
        self.label.setText(_translate("MainWindow", "KAT"))
        self.pushButton_abmelden.setText(_translate("MainWindow", "Abmelden"))
        self.label_2.setText(_translate("MainWindow", "Angemeldet:"))
        self.label_eingeloggt_als.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_passwort.setText(_translate("MainWindow", "Passwort ändern"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
