# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\Kopieren.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1524, 425)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_vor = QtWidgets.QPushButton(Dialog)
        self.pushButton_vor.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_vor.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_vor.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-left-arrow-button_icon-icons.com_72692.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_vor.setIcon(icon)
        self.pushButton_vor.setObjectName("pushButton_vor")
        self.horizontalLayout_2.addWidget(self.pushButton_vor)
        self.label_jahr = QtWidgets.QLabel(Dialog)
        self.label_jahr.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_jahr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jahr.setObjectName("label_jahr")
        self.horizontalLayout_2.addWidget(self.label_jahr)
        self.te_KW = QtWidgets.QLabel(Dialog)
        self.te_KW.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.te_KW.setObjectName("te_KW")
        self.horizontalLayout_2.addWidget(self.te_KW)
        self.pushButton_weiter = QtWidgets.QPushButton(Dialog)
        self.pushButton_weiter.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_weiter.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_weiter.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-right-arrow-button-1_icon-icons.com_72690.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_weiter.setIcon(icon1)
        self.pushButton_weiter.setObjectName("pushButton_weiter")
        self.horizontalLayout_2.addWidget(self.pushButton_weiter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_vor_E = QtWidgets.QPushButton(Dialog)
        self.pushButton_vor_E.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_vor_E.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_vor_E.setText("")
        self.pushButton_vor_E.setIcon(icon)
        self.pushButton_vor_E.setObjectName("pushButton_vor_E")
        self.horizontalLayout.addWidget(self.pushButton_vor_E)
        self.label_jahr_E = QtWidgets.QLabel(Dialog)
        self.label_jahr_E.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_jahr_E.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jahr_E.setObjectName("label_jahr_E")
        self.horizontalLayout.addWidget(self.label_jahr_E)
        self.te_KW_E = QtWidgets.QLabel(Dialog)
        self.te_KW_E.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.te_KW_E.setObjectName("te_KW_E")
        self.horizontalLayout.addWidget(self.te_KW_E)
        self.pushButton_weiter_E = QtWidgets.QPushButton(Dialog)
        self.pushButton_weiter_E.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_weiter_E.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_weiter_E.setText("")
        self.pushButton_weiter_E.setIcon(icon1)
        self.pushButton_weiter_E.setObjectName("pushButton_weiter_E")
        self.horizontalLayout.addWidget(self.pushButton_weiter_E)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_copy = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_copy.setObjectName("tableWidget_copy")
        self.tableWidget_copy.setColumnCount(0)
        self.tableWidget_copy.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget_copy)
        self.tableWidget_E = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_E.setObjectName("tableWidget_E")
        self.tableWidget_E.setColumnCount(0)
        self.tableWidget_E.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget_E)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_copy = QtWidgets.QPushButton(Dialog)
        self.pushButton_copy.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/copyblackinterfacesymboloftwopapersheets_79854.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_copy.setIcon(icon2)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.horizontalLayout_5.addWidget(self.pushButton_copy)
        self.pushButton_abbrechen = QtWidgets.QPushButton(Dialog)
        self.pushButton_abbrechen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/closewindowapplication_cerca_ventan_2874.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abbrechen.setIcon(icon3)
        self.pushButton_abbrechen.setObjectName("pushButton_abbrechen")
        self.horizontalLayout_5.addWidget(self.pushButton_abbrechen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Kopieren von KW:"))
        self.label_jahr.setText(_translate("Dialog", "TextLabel"))
        self.te_KW.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "Einsetzen in KW:"))
        self.label_jahr_E.setText(_translate("Dialog", "TextLabel"))
        self.te_KW_E.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_copy.setText(_translate("Dialog", "Kopieren und Einsetzen"))
        self.pushButton_abbrechen.setText(_translate("Dialog", "Abbrechen"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
