# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gornicec\Downloads\V1.5\Knapp_Apprentice_Training\sub\login\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(413, 204)
        Login.setStyleSheet("QPushButton:hover {\n"
"    border-width: 2px;\n"
"    cursor: pointer;\n"
"}\n"
"QPushButton:focus {\n"
"    border-width: 2px;\n"
"}\n"
"QPushButton{\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"background-color: #DDDDDD;\n"
"border-radius:4px;\n"
"}\n"
"QLineEdit{\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"background-color: #FFFFFF;\n"
"border-radius:4px;\n"
"}\n"
"QDialog{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(216, 216, 216, 255), stop:1 rgba(162, 162, 162, 255))\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.toolButton_nutzerverwaltung = QtWidgets.QToolButton(Login)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/black-male-user-symbol.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.toolButton_nutzerverwaltung.setIcon(icon)
        self.toolButton_nutzerverwaltung.setObjectName("toolButton_nutzerverwaltung")
        self.horizontalLayout_3.addWidget(self.toolButton_nutzerverwaltung)
        self.toolButton_einstellungen = QtWidgets.QToolButton(Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolButton_einstellungen.setFont(font)
        self.toolButton_einstellungen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\gornicec\\Downloads\\V1.5\\Knapp_Apprentice_Training\\sub\\login\\../../_Symbole/Icons/misc/1904675-configuration-edit-gear-options-preferences-setting-settings_122525 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_einstellungen.setIcon(icon1)
        self.toolButton_einstellungen.setObjectName("toolButton_einstellungen")
        self.horizontalLayout_3.addWidget(self.toolButton_einstellungen)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lineEdit_benutzername = QtWidgets.QLineEdit(Login)
        self.lineEdit_benutzername.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_benutzername.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_benutzername.setFont(font)
        self.lineEdit_benutzername.setObjectName("lineEdit_benutzername")
        self.horizontalLayout.addWidget(self.lineEdit_benutzername)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lineEdit_passwort = QtWidgets.QLineEdit(Login)
        self.lineEdit_passwort.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_passwort.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_passwort.setFont(font)
        self.lineEdit_passwort.setText("")
        self.lineEdit_passwort.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passwort.setObjectName("lineEdit_passwort")
        self.horizontalLayout_2.addWidget(self.lineEdit_passwort)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton_anmelden = QtWidgets.QPushButton(Login)
        self.pushButton_anmelden.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_anmelden.setFont(font)
        self.pushButton_anmelden.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\gornicec\\Downloads\\V1.5\\Knapp_Apprentice_Training\\sub\\login\\../../_Symbole/Icons/computer/log_in.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_anmelden.setIcon(icon2)
        self.pushButton_anmelden.setObjectName("pushButton_anmelden")
        self.verticalLayout.addWidget(self.pushButton_anmelden)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.lab_INFO = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_INFO.setFont(font)
        self.lab_INFO.setObjectName("lab_INFO")
        self.gridLayout.addWidget(self.lab_INFO, 2, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.lineEdit_benutzername, self.lineEdit_passwort)
        Login.setTabOrder(self.lineEdit_passwort, self.pushButton_anmelden)
        Login.setTabOrder(self.pushButton_anmelden, self.toolButton_einstellungen)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Knapp Apprentice Training"))
        self.label_3.setText(_translate("Login", "Melden sie sich an:"))
        self.toolButton_nutzerverwaltung.setText(_translate("Login", "..."))
        self.label.setText(_translate("Login", "Benutzername:"))
        self.label_2.setText(_translate("Login", "Passwort:"))
        self.pushButton_anmelden.setText(_translate("Login", "Anmelden"))
        self.lab_INFO.setText(_translate("Login", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
