# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\apprentice\apprentice_edit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApprenticeEdit(object):
    def setupUi(self, ApprenticeEdit):
        ApprenticeEdit.setObjectName("ApprenticeEdit")
        ApprenticeEdit.resize(800, 598)
        ApprenticeEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ApprenticeEdit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 11, 779, 42))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_vor_nach_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_vor_nach_name.setFont(font)
        self.label_vor_nach_name.setObjectName("label_vor_nach_name")
        self.horizontalLayout_3.addWidget(self.label_vor_nach_name)
        self.label_personalnummer = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_personalnummer.setFont(font)
        self.label_personalnummer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_personalnummer.setObjectName("label_personalnummer")
        self.horizontalLayout_3.addWidget(self.label_personalnummer)
        self.line = QtWidgets.QFrame(ApprenticeEdit)
        self.line.setGeometry(QtCore.QRect(10, 60, 779, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(ApprenticeEdit)
        self.groupBox.setGeometry(QtCore.QRect(30, 250, 351, 211))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 183))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_lj = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_lj.setObjectName("label_lj")
        self.horizontalLayout_5.addWidget(self.label_lj)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_lehrberuf = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_lehrberuf.setObjectName("comboBox_lehrberuf")
        self.horizontalLayout_6.addWidget(self.comboBox_lehrberuf)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_hauptmodul = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_hauptmodul.setObjectName("comboBox_hauptmodul")
        self.horizontalLayout_7.addWidget(self.comboBox_hauptmodul)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_spezialmodul = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_spezialmodul.setObjectName("comboBox_spezialmodul")
        self.horizontalLayout_8.addWidget(self.comboBox_spezialmodul)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.dateEdit_lehrbeginn = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.dateEdit_lehrbeginn.setObjectName("dateEdit_lehrbeginn")
        self.horizontalLayout_9.addWidget(self.dateEdit_lehrbeginn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.spinBox_lehrdauer = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox_lehrdauer.setObjectName("spinBox_lehrdauer")
        self.horizontalLayout_10.addWidget(self.spinBox_lehrdauer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.groupBox_4 = QtWidgets.QGroupBox(ApprenticeEdit)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 80, 351, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 20, 331, 121))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_29.addWidget(self.label_30)
        self.lineEdit_vorname = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.lineEdit_vorname.setObjectName("lineEdit_vorname")
        self.horizontalLayout_29.addWidget(self.lineEdit_vorname)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_21.addWidget(self.label_28)
        self.lineEdit_nachname = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.lineEdit_nachname.setObjectName("lineEdit_nachname")
        self.horizontalLayout_21.addWidget(self.lineEdit_nachname)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_26.addWidget(self.label_34)
        self.dateEdit_geburtsdatum = QtWidgets.QDateEdit(self.horizontalLayoutWidget_13)
        self.dateEdit_geburtsdatum.setObjectName("dateEdit_geburtsdatum")
        self.horizontalLayout_26.addWidget(self.dateEdit_geburtsdatum)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_27.addWidget(self.label_36)
        self.comboBox_geschlecht = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.comboBox_geschlecht.setObjectName("comboBox_geschlecht")
        self.comboBox_geschlecht.addItem("")
        self.comboBox_geschlecht.addItem("")
        self.horizontalLayout_27.addWidget(self.comboBox_geschlecht)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25.addLayout(self.verticalLayout_7)
        self.groupBox_3 = QtWidgets.QGroupBox(ApprenticeEdit)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 80, 351, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 331, 59))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_17.addWidget(self.label_25)
        self.lineEdit_mail = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.horizontalLayout_17.addWidget(self.lineEdit_mail)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.lineEdit_telefonnummer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_telefonnummer.setObjectName("lineEdit_telefonnummer")
        self.horizontalLayout_18.addWidget(self.lineEdit_telefonnummer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(ApprenticeEdit)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 190, 351, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 331, 152))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.lineEdit_strasse = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_strasse.setObjectName("lineEdit_strasse")
        self.horizontalLayout_12.addWidget(self.lineEdit_strasse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.lineEdit_hausnummer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_hausnummer.setObjectName("lineEdit_hausnummer")
        self.horizontalLayout_13.addWidget(self.lineEdit_hausnummer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.lineEdit_plz = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_plz.setObjectName("lineEdit_plz")
        self.horizontalLayout_14.addWidget(self.lineEdit_plz)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.lineEdit_ort = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_ort.setObjectName("lineEdit_ort")
        self.horizontalLayout_15.addWidget(self.lineEdit_ort)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.lineEdit_lkz = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_lkz.setObjectName("lineEdit_lkz")
        self.horizontalLayout_19.addWidget(self.lineEdit_lkz)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ApprenticeEdit)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(590, 550, 195, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_abbrechen = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_abbrechen.setObjectName("pushButton_abbrechen")
        self.horizontalLayout.addWidget(self.pushButton_abbrechen)
        self.pushButton_speichern = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_speichern.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pic/savetheapplication_guardar_2958.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_speichern.setIcon(icon)
        self.pushButton_speichern.setObjectName("pushButton_speichern")
        self.horizontalLayout.addWidget(self.pushButton_speichern)

        self.retranslateUi(ApprenticeEdit)
        QtCore.QMetaObject.connectSlotsByName(ApprenticeEdit)

    def retranslateUi(self, ApprenticeEdit):
        _translate = QtCore.QCoreApplication.translate
        ApprenticeEdit.setWindowTitle(_translate("ApprenticeEdit", "Lehrling bearbeiten"))
        self.label_vor_nach_name.setText(_translate("ApprenticeEdit", "Max Mustermann"))
        self.label_personalnummer.setText(_translate("ApprenticeEdit", "0000"))
        self.groupBox.setTitle(_translate("ApprenticeEdit", "Knapp:"))
        self.label_4.setText(_translate("ApprenticeEdit", "Lehrjahr:"))
        self.label_lj.setText(_translate("ApprenticeEdit", "TextLabel"))
        self.label_5.setText(_translate("ApprenticeEdit", "Lehrberuf:"))
        self.label_7.setText(_translate("ApprenticeEdit", "Hauptmodul:"))
        self.label_9.setText(_translate("ApprenticeEdit", "Spezialmodul:"))
        self.label_11.setText(_translate("ApprenticeEdit", "Lehrbeginn:"))
        self.label_13.setText(_translate("ApprenticeEdit", "Lehrdauer (Jahre):"))
        self.groupBox_4.setTitle(_translate("ApprenticeEdit", "Persönliches:"))
        self.label_30.setText(_translate("ApprenticeEdit", "Vorname:"))
        self.label_28.setText(_translate("ApprenticeEdit", "Nachname:"))
        self.label_34.setText(_translate("ApprenticeEdit", "Geburtsdatum:"))
        self.label_36.setText(_translate("ApprenticeEdit", "Geschlecht:"))
        self.comboBox_geschlecht.setItemText(0, _translate("ApprenticeEdit", "männlich"))
        self.comboBox_geschlecht.setItemText(1, _translate("ApprenticeEdit", "weiblich"))
        self.groupBox_3.setTitle(_translate("ApprenticeEdit", "Kontakt:"))
        self.label_25.setText(_translate("ApprenticeEdit", "Mail:"))
        self.label_27.setText(_translate("ApprenticeEdit", "Telefonnummer:"))
        self.groupBox_2.setTitle(_translate("ApprenticeEdit", "Adresse:"))
        self.label_15.setText(_translate("ApprenticeEdit", "Straße:"))
        self.label_17.setText(_translate("ApprenticeEdit", "Hausnummer:"))
        self.label_19.setText(_translate("ApprenticeEdit", "PLZ:"))
        self.label_21.setText(_translate("ApprenticeEdit", "Ort:"))
        self.label_23.setText(_translate("ApprenticeEdit", "LKZ:"))
        self.pushButton_abbrechen.setText(_translate("ApprenticeEdit", "Abbrechen"))
        self.pushButton_speichern.setText(_translate("ApprenticeEdit", "Speichern"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApprenticeEdit = QtWidgets.QDialog()
    ui = Ui_ApprenticeEdit()
    ui.setupUi(ApprenticeEdit)
    ApprenticeEdit.show()
    sys.exit(app.exec_())
