# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\lapcontent\LAP_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LAP_Themenkatalog_Suche(object):
    def setupUi(self, LAP_Themenkatalog_Suche):
        LAP_Themenkatalog_Suche.setObjectName("LAP_Themenkatalog_Suche")
        LAP_Themenkatalog_Suche.resize(713, 450)
        LAP_Themenkatalog_Suche.setMinimumSize(QtCore.QSize(713, 450))
        LAP_Themenkatalog_Suche.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(LAP_Themenkatalog_Suche)
        self.gridLayout.setObjectName("gridLayout")
        self.tW_LAP_Themenkatalog_DB = QtWidgets.QTableWidget(LAP_Themenkatalog_Suche)
        self.tW_LAP_Themenkatalog_DB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tW_LAP_Themenkatalog_DB.setFont(font)
        self.tW_LAP_Themenkatalog_DB.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tW_LAP_Themenkatalog_DB.setAlternatingRowColors(True)
        self.tW_LAP_Themenkatalog_DB.setObjectName("tW_LAP_Themenkatalog_DB")
        self.tW_LAP_Themenkatalog_DB.setColumnCount(0)
        self.tW_LAP_Themenkatalog_DB.setRowCount(0)
        self.tW_LAP_Themenkatalog_DB.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tW_LAP_Themenkatalog_DB, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(500)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_Suchen = QtWidgets.QPushButton(LAP_Themenkatalog_Suche)
        self.pB_Suchen.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Suchen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Suchen.setIcon(icon)
        self.pB_Suchen.setObjectName("pB_Suchen")
        self.horizontalLayout.addWidget(self.pB_Suchen)
        self.pB_Beenden = QtWidgets.QPushButton(LAP_Themenkatalog_Suche)
        self.pB_Beenden.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_Beenden.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Beenden.setIcon(icon1)
        self.pB_Beenden.setObjectName("pB_Beenden")
        self.horizontalLayout.addWidget(self.pB_Beenden)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_Suchbegriff = QtWidgets.QLabel(LAP_Themenkatalog_Suche)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Suchbegriff.setFont(font)
        self.lbl_Suchbegriff.setObjectName("lbl_Suchbegriff")
        self.horizontalLayout_2.addWidget(self.lbl_Suchbegriff)
        self.le_Suchbegriff = QtWidgets.QLineEdit(LAP_Themenkatalog_Suche)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_Suchbegriff.setFont(font)
        self.le_Suchbegriff.setObjectName("le_Suchbegriff")
        self.horizontalLayout_2.addWidget(self.le_Suchbegriff)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(LAP_Themenkatalog_Suche)
        QtCore.QMetaObject.connectSlotsByName(LAP_Themenkatalog_Suche)

    def retranslateUi(self, LAP_Themenkatalog_Suche):
        _translate = QtCore.QCoreApplication.translate
        LAP_Themenkatalog_Suche.setWindowTitle(_translate("LAP_Themenkatalog_Suche", "Suche"))
        self.pB_Suchen.setText(_translate("LAP_Themenkatalog_Suche", "Suchen"))
        self.pB_Beenden.setText(_translate("LAP_Themenkatalog_Suche", "Beenden"))
        self.lbl_Suchbegriff.setText(_translate("LAP_Themenkatalog_Suche", "Suchen:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LAP_Themenkatalog_Suche = QtWidgets.QDialog()
    ui = Ui_LAP_Themenkatalog_Suche()
    ui.setupUi(LAP_Themenkatalog_Suche)
    LAP_Themenkatalog_Suche.show()
    sys.exit(app.exec_())
