# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Projekte\Knapp_Apprentice_Training\sub\wochen_unterricht\Wochen_Unterricht.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1244, 887)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_Wochen_Plan = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_Wochen_Plan.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget_Wochen_Plan.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget_Wochen_Plan.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_Wochen_Plan.setLineWidth(1)
        self.tableWidget_Wochen_Plan.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_Wochen_Plan.setAutoScrollMargin(16)
        self.tableWidget_Wochen_Plan.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Wochen_Plan.setShowGrid(True)
        self.tableWidget_Wochen_Plan.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Wochen_Plan.setRowCount(12)
        self.tableWidget_Wochen_Plan.setObjectName("tableWidget_Wochen_Plan")
        self.tableWidget_Wochen_Plan.setColumnCount(0)
        self.tableWidget_Wochen_Plan.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_Wochen_Plan)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_hauptmenue = QtWidgets.QPushButton(Dialog)
        self.pushButton_hauptmenue.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/Icons/computer/log_out.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hauptmenue.setIcon(icon)
        self.pushButton_hauptmenue.setObjectName("pushButton_hauptmenue")
        self.horizontalLayout.addWidget(self.pushButton_hauptmenue)
        self.pushButton_copy = QtWidgets.QPushButton(Dialog)
        self.pushButton_copy.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/copyblackinterfacesymboloftwopapersheets_79854.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_copy.setIcon(icon1)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.horizontalLayout.addWidget(self.pushButton_copy)
        self.pushButton_excel_ausgabe = QtWidgets.QPushButton(Dialog)
        self.pushButton_excel_ausgabe.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/coordinated_assessment_documents_report_icon_148377.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_excel_ausgabe.setIcon(icon2)
        self.pushButton_excel_ausgabe.setObjectName("pushButton_excel_ausgabe")
        self.horizontalLayout.addWidget(self.pushButton_excel_ausgabe)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_Hilfe = QtWidgets.QPushButton(Dialog)
        self.pushButton_Hilfe.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/info_13213.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Hilfe.setIcon(icon3)
        self.pushButton_Hilfe.setObjectName("pushButton_Hilfe")
        self.horizontalLayout.addWidget(self.pushButton_Hilfe)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 7)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.te_KW = QtWidgets.QLabel(Dialog)
        self.te_KW.setMinimumSize(QtCore.QSize(30, 0))
        self.te_KW.setMaximumSize(QtCore.QSize(50, 16777215))
        self.te_KW.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.te_KW.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.te_KW.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.te_KW.setObjectName("te_KW")
        self.gridLayout.addWidget(self.te_KW, 1, 5, 1, 1)
        self.pushButton_befor_KW = QtWidgets.QPushButton(Dialog)
        self.pushButton_befor_KW.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_befor_KW.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-left-arrow-button_icon-icons.com_72692.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_befor_KW.setIcon(icon4)
        self.pushButton_befor_KW.setObjectName("pushButton_befor_KW")
        self.gridLayout.addWidget(self.pushButton_befor_KW, 1, 3, 1, 1)
        self.pushButton_next_KW = QtWidgets.QPushButton(Dialog)
        self.pushButton_next_KW.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_next_KW.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/keyboard-right-arrow-button-1_icon-icons.com_72690.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_KW.setIcon(icon5)
        self.pushButton_next_KW.setObjectName("pushButton_next_KW")
        self.gridLayout.addWidget(self.pushButton_next_KW, 1, 6, 1, 1)
        self.label_jahr = QtWidgets.QLabel(Dialog)
        self.label_jahr.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_jahr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_jahr.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label_jahr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jahr.setObjectName("label_jahr")
        self.gridLayout.addWidget(self.label_jahr, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tableWidget_Wochen_Plan.setSortingEnabled(False)
        self.pushButton_hauptmenue.setText(_translate("Dialog", "Hauptmenü"))
        self.pushButton_copy.setText(_translate("Dialog", "Kopieren"))
        self.pushButton_excel_ausgabe.setText(_translate("Dialog", "Daten Exportieren"))
        self.pushButton_Hilfe.setText(_translate("Dialog", "Hilfe"))
        self.te_KW.setText(_translate("Dialog", "."))
        self.label_jahr.setText(_translate("Dialog", "."))
        self.label.setText(_translate("Dialog", "Wochen Unterricht"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
