# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Knapp_Apprentice_Training\Knapp_Apprentice_Training\sub\field\Fachrichtungen_Suche.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suche_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(797, 707)
        Dialog.setMinimumSize(QtCore.QSize(797, 703))
        Dialog.setSizeGripEnabled(True)
        self.twAnzeige_suche = QtWidgets.QTableWidget(Dialog)
        self.twAnzeige_suche.setGeometry(QtCore.QRect(10, 140, 771, 551))
        self.twAnzeige_suche.setObjectName("twAnzeige_suche")
        self.twAnzeige_suche.setColumnCount(0)
        self.twAnzeige_suche.setRowCount(0)
        self.gbSuche = QtWidgets.QGroupBox(Dialog)
        self.gbSuche.setGeometry(QtCore.QRect(11, 16, 771, 111))
        self.gbSuche.setObjectName("gbSuche")
        self.btSuchen = QtWidgets.QPushButton(self.gbSuche)
        self.btSuchen.setGeometry(QtCore.QRect(550, 45, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/searchmagnifierinterfacesymbol1_79893.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSuchen.setIcon(icon)
        self.btSuchen.setObjectName("btSuchen")
        self.pB_BEENDEN = QtWidgets.QPushButton(self.gbSuche)
        self.pB_BEENDEN.setGeometry(QtCore.QRect(660, 45, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_Symbole/UsedSymbols/log-out_icon-icons.com_50106.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_BEENDEN.setIcon(icon1)
        self.pB_BEENDEN.setObjectName("pB_BEENDEN")
        self.lblFachrichtungbez2 = QtWidgets.QLabel(self.gbSuche)
        self.lblFachrichtungbez2.setGeometry(QtCore.QRect(280, 53, 101, 16))
        self.lblFachrichtungbez2.setObjectName("lblFachrichtungbez2")
        self.lblFahrichtungabk2 = QtWidgets.QLabel(self.gbSuche)
        self.lblFahrichtungabk2.setGeometry(QtCore.QRect(40, 53, 91, 16))
        self.lblFahrichtungabk2.setObjectName("lblFahrichtungabk2")
        self.leFachrichtungabk2 = QtWidgets.QLineEdit(self.gbSuche)
        self.leFachrichtungabk2.setGeometry(QtCore.QRect(130, 50, 113, 22))
        self.leFachrichtungabk2.setObjectName("leFachrichtungabk2")
        self.leFachrichtungbez2 = QtWidgets.QLineEdit(self.gbSuche)
        self.leFachrichtungbez2.setGeometry(QtCore.QRect(370, 50, 113, 22))
        self.leFachrichtungbez2.setObjectName("leFachrichtungbez2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Suche"))
        self.gbSuche.setTitle(_translate("Dialog", "Suche Fachrichtung:"))
        self.btSuchen.setText(_translate("Dialog", "Suchen"))
        self.pB_BEENDEN.setText(_translate("Dialog", "Beenden"))
        self.lblFachrichtungbez2.setText(_translate("Dialog", "Bezeichnung:"))
        self.lblFahrichtungabk2.setText(_translate("Dialog", "Fachrichtung:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Suche_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
