# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\thanner\Desktop\apprentice_management_system\sub\trainer\Ausbilder_suchen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ausbilder_suchen(object):
    def setupUi(self, Ausbilder_suchen):
        Ausbilder_suchen.setObjectName("Ausbilder_suchen")
        Ausbilder_suchen.resize(871, 706)
        Ausbilder_suchen.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Ausbilder_suchen)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_cancel = QtWidgets.QPushButton(Ausbilder_suchen)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(768, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Ausbilder_suchen)
        self.groupBox.setObjectName("groupBox")
        self.tw_suchen = QtWidgets.QTableWidget(self.groupBox)
        self.tw_suchen.setGeometry(QtCore.QRect(10, 20, 831, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_suchen.sizePolicy().hasHeightForWidth())
        self.tw_suchen.setSizePolicy(sizePolicy)
        self.tw_suchen.setObjectName("tw_suchen")
        self.tw_suchen.setColumnCount(0)
        self.tw_suchen.setRowCount(0)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 3)

        self.retranslateUi(Ausbilder_suchen)
        QtCore.QMetaObject.connectSlotsByName(Ausbilder_suchen)

    def retranslateUi(self, Ausbilder_suchen):
        _translate = QtCore.QCoreApplication.translate
        Ausbilder_suchen.setWindowTitle(_translate("Ausbilder_suchen", "Dialog"))
        self.pb_cancel.setText(_translate("Ausbilder_suchen", "Abbrechen"))
        self.groupBox.setTitle(_translate("Ausbilder_suchen", "Suchergebnis(e)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ausbilder_suchen = QtWidgets.QDialog()
    ui = Ui_Ausbilder_suchen()
    ui.setupUi(Ausbilder_suchen)
    Ausbilder_suchen.show()
    sys.exit(app.exec_())
